import { Country } from "./types";

export const countriesData: Country[] = [
  {
    name: "Japan",
    slug: "japan",
    code: "JP",
    capital: "Tokyo",
    region: "Asia",
    subregion: "Eastern Asia",
    population: 125800000,
    area: 377975,
    languages: ["Japanese"],
    currencies: [{ name: "Japanese yen", symbol: "¥" }],
    timezones: ["UTC+09:00"],
    flag: "https://flagcdn.com/w640/jp.png",
    coatOfArms: "",
    image: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=800&q=80",
    borders: [],
    drivingSide: "left",
    callingCode: "+81",
    tld: ".jp",
    independent: true,
    unMember: true,
    landlocked: false,
    safetyRating: "very-high",
    visaInfo: "Visa-free for 90 days for most Western countries. Work visa required for employment.",
    bestTimeToVisit: "March-May (cherry blossoms) and October-November (autumn foliage)",
    travelAdvisory: "Exercise normal precautions. Japan is one of the safest countries in the world.",
    plugType: "Type A, Type B (100V)",
    waterSafety: "Tap water is safe to drink throughout the country.",
    healthInfo: "No mandatory vaccinations. Excellent healthcare system. Travel insurance recommended.",
    emergencyNumber: "110 (Police), 119 (Fire/Ambulance)",
    lastUpdated: new Date().toISOString(),
  },
  {
    name: "France",
    slug: "france",
    code: "FR",
    capital: "Paris",
    region: "Europe",
    subregion: "Western Europe",
    population: 67390000,
    area: 551695,
    languages: ["French"],
    currencies: [{ name: "Euro", symbol: "€" }],
    timezones: ["UTC+01:00"],
    flag: "https://flagcdn.com/w640/fr.png",
    coatOfArms: "",
    image: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800&q=80",
    borders: ["AND", "BEL", "DEU", "ITA", "LUX", "MCO", "ESP", "CHE"],
    drivingSide: "right",
    callingCode: "+33",
    tld: ".fr",
    independent: true,
    unMember: true,
    landlocked: false,
    safetyRating: "high",
    visaInfo: "Schengen zone - 90-day visa-free for many nationalities. EU citizens have free movement.",
    bestTimeToVisit: "April-June and September-October for mild weather and fewer crowds",
    travelAdvisory: "Exercise increased caution due to occasional civil unrest and terrorism risks.",
    plugType: "Type C, Type E (230V)",
    waterSafety: "Tap water is safe to drink in all cities.",
    healthInfo: "European Health Insurance Card (EHIC) accepted for EU citizens. Routine vaccinations recommended.",
    emergencyNumber: "112 (General), 15 (Medical), 17 (Police)",
    lastUpdated: new Date().toISOString(),
  },
  {
    name: "Brazil",
    slug: "brazil",
    code: "BR",
    capital: "Brasília",
    region: "Americas",
    subregion: "South America",
    population: 214300000,
    area: 8515767,
    languages: ["Portuguese"],
    currencies: [{ name: "Brazilian real", symbol: "R$" }],
    timezones: ["UTC-05:00", "UTC-04:00", "UTC-03:00", "UTC-02:00"],
    flag: "https://flagcdn.com/w640/br.png",
    coatOfArms: "",
    image: "https://images.unsplash.com/photo-1483729558449-99ef09a8c325?w=800&q=80",
    borders: ["ARG", "BOL", "COL", "GUF", "GUY", "PRY", "PER", "SUR", "URY", "VEN"],
    drivingSide: "right",
    callingCode: "+55",
    tld: ".br",
    independent: true,
    unMember: true,
    landlocked: false,
    safetyRating: "moderate",
    visaInfo: "Visa-free for up to 90 days for many nationalities. E-visa available for US citizens.",
    bestTimeToVisit: "December-March for beaches and Carnival; June-September for cooler weather",
    travelAdvisory: "Exercise increased caution due to crime. Avoid isolated areas at night.",
    plugType: "Type C, Type N (127/220V)",
    waterSafety: "Drink bottled or filtered water. Tap water varies by region.",
    healthInfo: "Yellow fever vaccination recommended. Malaria prophylaxis for Amazon region.",
    emergencyNumber: "190 (Police), 192 (Ambulance), 193 (Fire)",
    lastUpdated: new Date().toISOString(),
  },
  {
    name: "Australia",
    slug: "australia",
    code: "AU",
    capital: "Canberra",
    region: "Oceania",
    subregion: "Australia and New Zealand",
    population: 26400000,
    area: 7692024,
    languages: ["English"],
    currencies: [{ name: "Australian dollar", symbol: "$" }],
    timezones: ["UTC+08:00", "UTC+09:30", "UTC+10:00", "UTC+10:30", "UTC+11:00"],
    flag: "https://flagcdn.com/w640/au.png",
    coatOfArms: "",
    image: "https://images.unsplash.com/photo-1523482580672-f109ba8cb9be?w=800&q=80",
    borders: [],
    drivingSide: "left",
    callingCode: "+61",
    tld: ".au",
    independent: true,
    unMember: true,
    landlocked: false,
    safetyRating: "very-high",
    visaInfo: "ETA (Electronic Travel Authority) required for most visitors. Apply online before travel.",
    bestTimeToVisit: "September-November (spring) and March-May (autumn) for most regions",
    travelAdvisory: "Exercise normal precautions. Be aware of natural hazards including bushfires and marine life.",
    plugType: "Type I (230V)",
    waterSafety: "Tap water is safe to drink in all major cities.",
    healthInfo: "No mandatory vaccinations. Sun protection essential. Watch for dangerous wildlife.",
    emergencyNumber: "000 (General), 112 (Mobile)",
    lastUpdated: new Date().toISOString(),
  },
  {
    name: "Italy",
    slug: "italy",
    code: "IT",
    capital: "Rome",
    region: "Europe",
    subregion: "Southern Europe",
    population: 59550000,
    area: 301336,
    languages: ["Italian"],
    currencies: [{ name: "Euro", symbol: "€" }],
    timezones: ["UTC+01:00"],
    flag: "https://flagcdn.com/w640/it.png",
    coatOfArms: "",
    image: "https://images.unsplash.com/photo-1523906834658-6e24ef2386f9?w=800&q=80",
    borders: ["AUT", "FRA", "SMR", "SVN", "CHE", "VAT"],
    drivingSide: "right",
    callingCode: "+39",
    tld: ".it",
    independent: true,
    unMember: true,
    landlocked: false,
    safetyRating: "high",
    visaInfo: "Schengen zone - 90-day visa-free for many nationalities. EU citizens have free movement.",
    bestTimeToVisit: "April-June and September-October for pleasant weather and fewer tourists",
    travelAdvisory: "Exercise normal precautions. Be aware of pickpockets in tourist areas.",
    plugType: "Type C, Type F, Type L (230V)",
    waterSafety: "Tap water is safe to drink. Public fountains available in Rome.",
    healthInfo: "EHIC accepted for EU citizens. Routine vaccinations recommended.",
    emergencyNumber: "112 (General), 113 (Police), 118 (Ambulance)",
    lastUpdated: new Date().toISOString(),
  },
  {
    name: "Thailand",
    slug: "thailand",
    code: "TH",
    capital: "Bangkok",
    region: "Asia",
    subregion: "South-Eastern Asia",
    population: 71800000,
    area: 513120,
    languages: ["Thai"],
    currencies: [{ name: "Thai baht", symbol: "฿" }],
    timezones: ["UTC+07:00"],
    flag: "https://flagcdn.com/w640/th.png",
    coatOfArms: "",
    image: "https://images.unsplash.com/photo-1528181304800-259b08848526?w=800&q=80",
    borders: ["MMR", "KHM", "LAO", "MYS"],
    drivingSide: "left",
    callingCode: "+66",
    tld: ".th",
    independent: true,
    unMember: true,
    landlocked: false,
    safetyRating: "high",
    visaInfo: "Visa-free for 30 days for many nationalities. Visa on arrival for 15 days. Extensions possible.",
    bestTimeToVisit: "November-February (cool season). Avoid monsoon months June-October.",
    travelAdvisory: "Exercise increased caution. Be respectful of the monarchy and Buddhist customs.",
    plugType: "Type A, B, C, F, O (220V)",
    waterSafety: "Do not drink tap water. Use bottled or filtered water.",
    healthInfo: "Hepatitis A and Typhoid vaccines recommended. Dengue fever risk - use insect repellent.",
    emergencyNumber: "191 (Police), 1669 (Ambulance), 199 (Fire)",
    lastUpdated: new Date().toISOString(),
  },
  {
    name: "Mexico",
    slug: "mexico",
    code: "MX",
    capital: "Mexico City",
    region: "Americas",
    subregion: "North America",
    population: 128900000,
    area: 1964375,
    languages: ["Spanish"],
    currencies: [{ name: "Mexican peso", symbol: "$" }],
    timezones: ["UTC-08:00", "UTC-07:00", "UTC-06:00", "UTC-05:00"],
    flag: "https://flagcdn.com/w640/mx.png",
    coatOfArms: "",
    image: "https://images.unsplash.com/photo-1518638150340-f706e86654de?w=800&q=80",
    borders: ["BLZ", "GTM", "USA"],
    drivingSide: "right",
    callingCode: "+52",
    tld: ".mx",
    independent: true,
    unMember: true,
    landlocked: false,
    safetyRating: "moderate",
    visaInfo: "Visa-free for up to 180 days for most Western countries. FMM tourist card required.",
    bestTimeToVisit: "December-April for dry season. October-November for Day of the Dead.",
    travelAdvisory: "Exercise increased caution. Avoid certain states due to crime. Research specific areas.",
    plugType: "Type A, Type B (127V)",
    waterSafety: "Do not drink tap water. Use bottled water everywhere.",
    healthInfo: "Hepatitis A vaccine recommended. Watch for altitude sickness in Mexico City.",
    emergencyNumber: "911 (General)",
    lastUpdated: new Date().toISOString(),
  },
  {
    name: "United Kingdom",
    slug: "united-kingdom",
    code: "GB",
    capital: "London",
    region: "Europe",
    subregion: "Northern Europe",
    population: 67886011,
    area: 242900,
    languages: ["English"],
    currencies: [{ name: "British pound", symbol: "£" }],
    timezones: ["UTC+00:00"],
    flag: "https://flagcdn.com/w640/gb.png",
    coatOfArms: "",
    image: "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=800&q=80",
    borders: ["IRL"],
    drivingSide: "left",
    callingCode: "+44",
    tld: ".uk",
    independent: true,
    unMember: true,
    landlocked: false,
    safetyRating: "high",
    visaInfo: "Visa-free for up to 6 months for most Western countries. Electronic Travel Authorisation (ETA) being introduced.",
    bestTimeToVisit: "May-September for warmest weather. December for Christmas markets.",
    travelAdvisory: "Exercise normal precautions. Be aware of pickpockets in London tourist areas.",
    plugType: "Type G (230V)",
    waterSafety: "Tap water is safe to drink throughout the country.",
    healthInfo: "NHS available for emergencies. GHIC/EHIC for EU citizens. Travel insurance recommended.",
    emergencyNumber: "999 (General), 112 (EU standard)",
    lastUpdated: new Date().toISOString(),
  },
  {
    name: "South Korea",
    slug: "south-korea",
    code: "KR",
    capital: "Seoul",
    region: "Asia",
    subregion: "Eastern Asia",
    population: 51780000,
    area: 100210,
    languages: ["Korean"],
    currencies: [{ name: "South Korean won", symbol: "₩" }],
    timezones: ["UTC+09:00"],
    flag: "https://flagcdn.com/w640/kr.png",
    coatOfArms: "",
    image: "https://images.unsplash.com/photo-1517154421773-0529f29ea451?w=800&q=80",
    borders: ["PRK"],
    drivingSide: "right",
    callingCode: "+82",
    tld: ".kr",
    independent: true,
    unMember: true,
    landlocked: false,
    safetyRating: "very-high",
    visaInfo: "K-ETA required for visa-free entry (up to 90 days) for many nationalities.",
    bestTimeToVisit: "April-June (spring) and September-November (autumn) for best weather",
    travelAdvisory: "Exercise normal precautions. One of the safest countries in Asia.",
    plugType: "Type C, Type F (220V)",
    waterSafety: "Tap water is technically safe but most locals drink filtered water.",
    healthInfo: "No mandatory vaccinations. Excellent healthcare system. Air quality can be poor in spring.",
    emergencyNumber: "112 (General), 119 (Fire/Ambulance)",
    lastUpdated: new Date().toISOString(),
  },
  {
    name: "Egypt",
    slug: "egypt",
    code: "EG",
    capital: "Cairo",
    region: "Africa",
    subregion: "Northern Africa",
    population: 104300000,
    area: 1002450,
    languages: ["Arabic"],
    currencies: [{ name: "Egyptian pound", symbol: "E£" }],
    timezones: ["UTC+02:00"],
    flag: "https://flagcdn.com/w640/eg.png",
    coatOfArms: "",
    image: "https://images.unsplash.com/photo-1572252009286-268acec5ca0a?w=800&q=80",
    borders: ["ISR", "LBY", "PSE", "SDN"],
    drivingSide: "right",
    callingCode: "+20",
    tld: ".eg",
    independent: true,
    unMember: true,
    landlocked: false,
    safetyRating: "moderate",
    visaInfo: "Visa on arrival available for many nationalities ($25 USD). E-visa also available.",
    bestTimeToVisit: "October-April for cooler temperatures. Avoid summer heat (June-August).",
    travelAdvisory: "Exercise increased caution. Avoid Sinai Peninsula border areas.",
    plugType: "Type C, Type F (220V)",
    waterSafety: "Do not drink tap water. Use bottled water.",
    healthInfo: "Hepatitis A and Typhoid vaccines recommended. Beware of heat stroke in summer.",
    emergencyNumber: "122 (Police), 123 (Ambulance), 180 (Fire)",
    lastUpdated: new Date().toISOString(),
  },
  {
    name: "Germany",
    slug: "germany",
    code: "DE",
    capital: "Berlin",
    region: "Europe",
    subregion: "Western Europe",
    population: 83240000,
    area: 357114,
    languages: ["German"],
    currencies: [{ name: "Euro", symbol: "€" }],
    timezones: ["UTC+01:00"],
    flag: "https://flagcdn.com/w640/de.png",
    coatOfArms: "",
    image: "https://images.unsplash.com/photo-1467269204594-9661b134dd2b?w=800&q=80",
    borders: ["AUT", "BEL", "CZE", "DNK", "FRA", "LUX", "NLD", "POL", "CHE"],
    drivingSide: "right",
    callingCode: "+49",
    tld: ".de",
    independent: true,
    unMember: true,
    landlocked: false,
    safetyRating: "very-high",
    visaInfo: "Schengen zone - 90-day visa-free for many nationalities.",
    bestTimeToVisit: "May-September for warm weather. December for Christmas markets.",
    travelAdvisory: "Exercise normal precautions. Very safe country overall.",
    plugType: "Type C, Type F (230V)",
    waterSafety: "Tap water is safe to drink and high quality.",
    healthInfo: "EHIC accepted for EU citizens. Excellent healthcare system.",
    emergencyNumber: "112 (General), 110 (Police)",
    lastUpdated: new Date().toISOString(),
  },
  {
    name: "Canada",
    slug: "canada",
    code: "CA",
    capital: "Ottawa",
    region: "Americas",
    subregion: "North America",
    population: 40100000,
    area: 9984670,
    languages: ["English", "French"],
    currencies: [{ name: "Canadian dollar", symbol: "$" }],
    timezones: ["UTC-08:00", "UTC-07:00", "UTC-06:00", "UTC-05:00", "UTC-04:00", "UTC-03:30"],
    flag: "https://flagcdn.com/w640/ca.png",
    coatOfArms: "",
    image: "https://images.unsplash.com/photo-1517935706615-2717063c2225?w=800&q=80",
    borders: ["USA"],
    drivingSide: "right",
    callingCode: "+1",
    tld: ".ca",
    independent: true,
    unMember: true,
    landlocked: false,
    safetyRating: "very-high",
    visaInfo: "eTA required for visa-exempt nationals flying to Canada. Visa required for some nationalities.",
    bestTimeToVisit: "June-August for outdoor activities. December-March for skiing.",
    travelAdvisory: "Exercise normal precautions. Very safe country.",
    plugType: "Type A, Type B (120V)",
    waterSafety: "Tap water is safe to drink throughout the country.",
    healthInfo: "No mandatory vaccinations. Travel insurance strongly recommended as healthcare is expensive for visitors.",
    emergencyNumber: "911 (General)",
    lastUpdated: new Date().toISOString(),
  },
  {
    name: "India",
    slug: "india",
    code: "IN",
    capital: "New Delhi",
    region: "Asia",
    subregion: "Southern Asia",
    population: 1428600000,
    area: 3287263,
    languages: ["Hindi", "English"],
    currencies: [{ name: "Indian rupee", symbol: "₹" }],
    timezones: ["UTC+05:30"],
    flag: "https://flagcdn.com/w640/in.png",
    coatOfArms: "",
    image: "https://images.unsplash.com/photo-1524492412937-b28074a5d7da?w=800&q=80",
    borders: ["BGD", "BTN", "MMR", "CHN", "NPL", "PAK"],
    drivingSide: "left",
    callingCode: "+91",
    tld: ".in",
    independent: true,
    unMember: true,
    landlocked: false,
    safetyRating: "moderate",
    visaInfo: "E-visa available for most nationalities. Apply at least 4 days before travel.",
    bestTimeToVisit: "October-March for most regions. Varies greatly by area.",
    travelAdvisory: "Exercise increased caution. Be aware of scams in tourist areas.",
    plugType: "Type C, Type D, Type M (230V)",
    waterSafety: "Do not drink tap water. Use bottled or filtered water everywhere.",
    healthInfo: "Hepatitis A, Typhoid, and routine vaccinations recommended. Malaria prophylaxis for some regions.",
    emergencyNumber: "112 (General), 100 (Police), 102 (Ambulance)",
    lastUpdated: new Date().toISOString(),
  },
  {
    name: "Spain",
    slug: "spain",
    code: "ES",
    capital: "Madrid",
    region: "Europe",
    subregion: "Southern Europe",
    population: 47420000,
    area: 505992,
    languages: ["Spanish"],
    currencies: [{ name: "Euro", symbol: "€" }],
    timezones: ["UTC+01:00"],
    flag: "https://flagcdn.com/w640/es.png",
    coatOfArms: "",
    image: "https://images.unsplash.com/photo-1543783207-ec64e4d95325?w=800&q=80",
    borders: ["AND", "FRA", "GIB", "PRT", "MAR"],
    drivingSide: "right",
    callingCode: "+34",
    tld: ".es",
    independent: true,
    unMember: true,
    landlocked: false,
    safetyRating: "high",
    visaInfo: "Schengen zone - 90-day visa-free for many nationalities.",
    bestTimeToVisit: "April-June and September-November for mild weather.",
    travelAdvisory: "Exercise normal precautions. Beware of pickpockets in Barcelona and Madrid.",
    plugType: "Type C, Type F (230V)",
    waterSafety: "Tap water is safe in most areas. Some coastal areas have a chlorinated taste.",
    healthInfo: "EHIC accepted for EU citizens. No special vaccinations required.",
    emergencyNumber: "112 (General)",
    lastUpdated: new Date().toISOString(),
  },
  {
    name: "South Africa",
    slug: "south-africa",
    code: "ZA",
    capital: "Pretoria",
    region: "Africa",
    subregion: "Southern Africa",
    population: 60600000,
    area: 1221037,
    languages: ["Afrikaans", "English", "Zulu", "Xhosa"],
    currencies: [{ name: "South African rand", symbol: "R" }],
    timezones: ["UTC+02:00"],
    flag: "https://flagcdn.com/w640/za.png",
    coatOfArms: "",
    image: "https://images.unsplash.com/photo-1580060839134-75a5edca2e99?w=800&q=80",
    borders: ["BWA", "LSO", "MOZ", "NAM", "SWZ", "ZWE"],
    drivingSide: "left",
    callingCode: "+27",
    tld: ".za",
    independent: true,
    unMember: true,
    landlocked: false,
    safetyRating: "moderate",
    visaInfo: "Visa-free for up to 90 days for many nationalities.",
    bestTimeToVisit: "May-September (dry winter) for wildlife. November-March for beaches.",
    travelAdvisory: "Exercise increased caution due to crime. Avoid walking alone at night.",
    plugType: "Type M, Type N (230V)",
    waterSafety: "Tap water is safe in major cities. Use bottled water in rural areas.",
    healthInfo: "Yellow fever vaccine if coming from endemic area. Malaria prophylaxis for Kruger area.",
    emergencyNumber: "10111 (Police), 10177 (Ambulance)",
    lastUpdated: new Date().toISOString(),
  },
  {
    name: "Greece",
    slug: "greece",
    code: "GR",
    capital: "Athens",
    region: "Europe",
    subregion: "Southern Europe",
    population: 10720000,
    area: 131957,
    languages: ["Greek"],
    currencies: [{ name: "Euro", symbol: "€" }],
    timezones: ["UTC+02:00"],
    flag: "https://flagcdn.com/w640/gr.png",
    coatOfArms: "",
    image: "https://images.unsplash.com/photo-1533105079780-92b9be482077?w=800&q=80",
    borders: ["ALB", "BGR", "TUR", "MKD"],
    drivingSide: "right",
    callingCode: "+30",
    tld: ".gr",
    independent: true,
    unMember: true,
    landlocked: false,
    safetyRating: "high",
    visaInfo: "Schengen zone - 90-day visa-free for many nationalities.",
    bestTimeToVisit: "April-June and September-October. July-August is peak season and very hot.",
    travelAdvisory: "Exercise normal precautions. Beware of pickpockets at tourist sites.",
    plugType: "Type C, Type F (230V)",
    waterSafety: "Tap water safe on mainland. Use bottled water on some islands.",
    healthInfo: "EHIC accepted for EU citizens. Sun protection essential in summer.",
    emergencyNumber: "112 (General), 100 (Police), 166 (Ambulance)",
    lastUpdated: new Date().toISOString(),
  },
  {
    name: "Morocco",
    slug: "morocco",
    code: "MA",
    capital: "Rabat",
    region: "Africa",
    subregion: "Northern Africa",
    population: 37080000,
    area: 446550,
    languages: ["Arabic", "Berber"],
    currencies: [{ name: "Moroccan dirham", symbol: "MAD" }],
    timezones: ["UTC+01:00"],
    flag: "https://flagcdn.com/w640/ma.png",
    coatOfArms: "",
    image: "https://images.unsplash.com/photo-1489749798305-4fea3ae63d43?w=800&q=80",
    borders: ["DZA", "ESH", "ESP"],
    drivingSide: "right",
    callingCode: "+212",
    tld: ".ma",
    independent: true,
    unMember: true,
    landlocked: false,
    safetyRating: "high",
    visaInfo: "Visa-free for up to 90 days for most Western countries.",
    bestTimeToVisit: "March-May and September-November for mild weather.",
    travelAdvisory: "Exercise normal precautions. Bargain in souks; be aware of common scams.",
    plugType: "Type C, Type E (220V)",
    waterSafety: "Do not drink tap water. Use bottled water.",
    healthInfo: "Hepatitis A vaccine recommended. Be cautious with street food.",
    emergencyNumber: "19 (Police), 15 (Ambulance)",
    lastUpdated: new Date().toISOString(),
  },
  {
    name: "New Zealand",
    slug: "new-zealand",
    code: "NZ",
    capital: "Wellington",
    region: "Oceania",
    subregion: "Australia and New Zealand",
    population: 5185000,
    area: 270467,
    languages: ["English", "Māori"],
    currencies: [{ name: "New Zealand dollar", symbol: "$" }],
    timezones: ["UTC+12:00", "UTC+12:45"],
    flag: "https://flagcdn.com/w640/nz.png",
    coatOfArms: "",
    image: "https://images.unsplash.com/photo-1469521669194-babb45599def?w=800&q=80",
    borders: [],
    drivingSide: "left",
    callingCode: "+64",
    tld: ".nz",
    independent: true,
    unMember: true,
    landlocked: false,
    safetyRating: "very-high",
    visaInfo: "NZeTA required for visa waiver nationalities. Apply before travel.",
    bestTimeToVisit: "December-February (summer). Year-round for different activities.",
    travelAdvisory: "Exercise normal precautions. Very safe destination.",
    plugType: "Type I (230V)",
    waterSafety: "Tap water is safe to drink throughout the country.",
    healthInfo: "No mandatory vaccinations. Sun protection essential - high UV levels.",
    emergencyNumber: "111 (General)",
    lastUpdated: new Date().toISOString(),
  },
  {
    name: "Turkey",
    slug: "turkey",
    code: "TR",
    capital: "Ankara",
    region: "Asia",
    subregion: "Western Asia",
    population: 85280000,
    area: 783562,
    languages: ["Turkish"],
    currencies: [{ name: "Turkish lira", symbol: "₺" }],
    timezones: ["UTC+03:00"],
    flag: "https://flagcdn.com/w640/tr.png",
    coatOfArms: "",
    image: "https://images.unsplash.com/photo-1541432901042-2d8bd64b4a9b?w=800&q=80",
    borders: ["ARM", "AZE", "BGR", "GEO", "GRC", "IRN", "IRQ", "SYR"],
    drivingSide: "right",
    callingCode: "+90",
    tld: ".tr",
    independent: true,
    unMember: true,
    landlocked: false,
    safetyRating: "high",
    visaInfo: "E-visa required for many nationalities. Apply online. Some get visa-free entry.",
    bestTimeToVisit: "April-June and September-November for mild weather.",
    travelAdvisory: "Exercise increased caution near borders. Major tourist areas are generally safe.",
    plugType: "Type C, Type F (220V)",
    waterSafety: "Do not drink tap water in most areas. Bottled water recommended.",
    healthInfo: "Routine vaccinations recommended. Hepatitis A for some travelers.",
    emergencyNumber: "112 (General), 155 (Police), 112 (Ambulance)",
    lastUpdated: new Date().toISOString(),
  },
  {
    name: "Portugal",
    slug: "portugal",
    code: "PT",
    capital: "Lisbon",
    region: "Europe",
    subregion: "Southern Europe",
    population: 10310000,
    area: 92212,
    languages: ["Portuguese"],
    currencies: [{ name: "Euro", symbol: "€" }],
    timezones: ["UTC+00:00", "UTC-01:00"],
    flag: "https://flagcdn.com/w640/pt.png",
    coatOfArms: "",
    image: "https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=800&q=80",
    borders: ["ESP"],
    drivingSide: "right",
    callingCode: "+351",
    tld: ".pt",
    independent: true,
    unMember: true,
    landlocked: false,
    safetyRating: "very-high",
    visaInfo: "Schengen zone - 90-day visa-free for many nationalities.",
    bestTimeToVisit: "March-May and September-October for pleasant weather and fewer crowds.",
    travelAdvisory: "Exercise normal precautions. One of the safest countries in Europe.",
    plugType: "Type C, Type F (230V)",
    waterSafety: "Tap water is safe to drink throughout the country.",
    healthInfo: "EHIC accepted for EU citizens. No special vaccinations required.",
    emergencyNumber: "112 (General)",
    lastUpdated: new Date().toISOString(),
  },
  {
    name: "Switzerland",
    slug: "switzerland",
    code: "CH",
    capital: "Bern",
    region: "Europe",
    subregion: "Western Europe",
    population: 8776000,
    area: 41284,
    languages: ["German", "French", "Italian", "Romansh"],
    currencies: [{ name: "Swiss franc", symbol: "CHF" }],
    timezones: ["UTC+01:00"],
    flag: "https://flagcdn.com/w640/ch.png",
    coatOfArms: "",
    image: "https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?w=800&q=80",
    borders: ["AUT", "FRA", "ITA", "LIE", "DEU"],
    drivingSide: "right",
    callingCode: "+41",
    tld: ".ch",
    independent: true,
    unMember: true,
    landlocked: true,
    safetyRating: "very-high",
    visaInfo: "Schengen zone - 90-day visa-free for many nationalities. Not an EU member but part of Schengen.",
    bestTimeToVisit: "June-September for hiking; December-March for skiing. Fall is beautiful.",
    travelAdvisory: "Exercise normal precautions. Extremely safe country.",
    plugType: "Type J (230V)",
    waterSafety: "Tap water is excellent quality throughout the country.",
    healthInfo: "No mandatory vaccinations. World-class healthcare system. Travel insurance essential due to high costs.",
    emergencyNumber: "112 (General), 117 (Police), 144 (Ambulance)",
    lastUpdated: new Date().toISOString(),
  },
  {
    name: "Vietnam",
    slug: "vietnam",
    code: "VN",
    capital: "Hanoi",
    region: "Asia",
    subregion: "South-Eastern Asia",
    population: 99460000,
    area: 331212,
    languages: ["Vietnamese"],
    currencies: [{ name: "Vietnamese dong", symbol: "₫" }],
    timezones: ["UTC+07:00"],
    flag: "https://flagcdn.com/w640/vn.png",
    coatOfArms: "",
    image: "https://images.unsplash.com/photo-1528127269322-539801943592?w=800&q=80",
    borders: ["KHM", "CHN", "LAO"],
    drivingSide: "right",
    callingCode: "+84",
    tld: ".vn",
    independent: true,
    unMember: true,
    landlocked: false,
    safetyRating: "high",
    visaInfo: "E-visa available for most nationalities (30 days). Visa-free for some ASEAN countries.",
    bestTimeToVisit: "October-April for the south; March-May for the north. Varies by region.",
    travelAdvisory: "Exercise normal precautions. Very friendly to tourists. Be cautious of traffic.",
    plugType: "Type A, C, F (220V)",
    waterSafety: "Do not drink tap water. Bottled water widely available and cheap.",
    healthInfo: "Hepatitis A and Typhoid vaccines recommended. Dengue risk in some areas.",
    emergencyNumber: "113 (Police), 115 (Ambulance), 114 (Fire)",
    lastUpdated: new Date().toISOString(),
  },
  {
    name: "Argentina",
    slug: "argentina",
    code: "AR",
    capital: "Buenos Aires",
    region: "Americas",
    subregion: "South America",
    population: 45810000,
    area: 2780400,
    languages: ["Spanish"],
    currencies: [{ name: "Argentine peso", symbol: "$" }],
    timezones: ["UTC-03:00"],
    flag: "https://flagcdn.com/w640/ar.png",
    coatOfArms: "",
    image: "https://images.unsplash.com/photo-1589909202802-8f4aadce1849?w=800&q=80",
    borders: ["BOL", "BRA", "CHL", "PRY", "URY"],
    drivingSide: "right",
    callingCode: "+54",
    tld: ".ar",
    independent: true,
    unMember: true,
    landlocked: false,
    safetyRating: "moderate",
    visaInfo: "Visa-free for up to 90 days for most Western nationalities.",
    bestTimeToVisit: "October-April for Patagonia; March-May for Buenos Aires; June-August for skiing.",
    travelAdvisory: "Exercise increased caution. Petty theft common in Buenos Aires. Avoid protests.",
    plugType: "Type C, Type I (220V)",
    waterSafety: "Tap water is safe in Buenos Aires and major cities.",
    healthInfo: "Routine vaccinations recommended. Yellow fever if visiting Iguazu Falls area.",
    emergencyNumber: "911 (General)",
    lastUpdated: new Date().toISOString(),
  },
  {
    name: "Colombia",
    slug: "colombia",
    code: "CO",
    capital: "Bogota",
    region: "Americas",
    subregion: "South America",
    population: 51870000,
    area: 1141748,
    languages: ["Spanish"],
    currencies: [{ name: "Colombian peso", symbol: "$" }],
    timezones: ["UTC-05:00"],
    flag: "https://flagcdn.com/w640/co.png",
    coatOfArms: "",
    image: "https://images.unsplash.com/photo-1568632234157-ce7aecd03d0d?w=800&q=80",
    borders: ["BRA", "ECU", "PAN", "PER", "VEN"],
    drivingSide: "right",
    callingCode: "+57",
    tld: ".co",
    independent: true,
    unMember: true,
    landlocked: false,
    safetyRating: "moderate",
    visaInfo: "Visa-free for 90 days for most Western nationalities. Extendable once.",
    bestTimeToVisit: "December-March and July-August are driest. Weather varies by altitude.",
    travelAdvisory: "Exercise increased caution. Tourist areas in major cities are generally safe.",
    plugType: "Type A, Type B (110V)",
    waterSafety: "Tap water safe in Bogota. Use bottled water in smaller towns.",
    healthInfo: "Yellow fever vaccine if visiting jungle areas. Altitude sickness possible in Bogota.",
    emergencyNumber: "123 (General)",
    lastUpdated: new Date().toISOString(),
  },
  {
    name: "Peru",
    slug: "peru",
    code: "PE",
    capital: "Lima",
    region: "Americas",
    subregion: "South America",
    population: 33720000,
    area: 1285216,
    languages: ["Spanish", "Quechua", "Aymara"],
    currencies: [{ name: "Peruvian sol", symbol: "S/" }],
    timezones: ["UTC-05:00"],
    flag: "https://flagcdn.com/w640/pe.png",
    coatOfArms: "",
    image: "https://images.unsplash.com/photo-1526392060635-9d6019884377?w=800&q=80",
    borders: ["BOL", "BRA", "CHL", "COL", "ECU"],
    drivingSide: "right",
    callingCode: "+51",
    tld: ".pe",
    independent: true,
    unMember: true,
    landlocked: false,
    safetyRating: "moderate",
    visaInfo: "Visa-free for up to 183 days for most nationalities.",
    bestTimeToVisit: "May-September (dry season) for Machu Picchu and Cusco. Lima is best Dec-April.",
    travelAdvisory: "Exercise increased caution. Petty theft in tourist areas. Altitude sickness above 2500m.",
    plugType: "Type A, Type B, Type C (220V)",
    waterSafety: "Do not drink tap water. Use bottled or boiled water everywhere.",
    healthInfo: "Hepatitis A, Typhoid recommended. Altitude sickness medication for highlands.",
    emergencyNumber: "105 (Police), 116 (Fire), 106 (Ambulance)",
    lastUpdated: new Date().toISOString(),
  },
  {
    name: "Iceland",
    slug: "iceland",
    code: "IS",
    capital: "Reykjavik",
    region: "Europe",
    subregion: "Northern Europe",
    population: 376248,
    area: 103000,
    languages: ["Icelandic"],
    currencies: [{ name: "Icelandic krona", symbol: "kr" }],
    timezones: ["UTC+00:00"],
    flag: "https://flagcdn.com/w640/is.png",
    coatOfArms: "",
    image: "https://images.unsplash.com/photo-1504829857797-ddff29c27927?w=800&q=80",
    borders: [],
    drivingSide: "right",
    callingCode: "+354",
    tld: ".is",
    independent: true,
    unMember: true,
    landlocked: false,
    safetyRating: "very-high",
    visaInfo: "Schengen zone - 90-day visa-free for many nationalities.",
    bestTimeToVisit: "June-August for midnight sun and hiking. September-March for Northern Lights.",
    travelAdvisory: "Exercise normal precautions. One of the safest countries in the world. Weather can be extreme.",
    plugType: "Type C, Type F (230V)",
    waterSafety: "Tap water is some of the purest in the world.",
    healthInfo: "No mandatory vaccinations. Pack warm layers. Road conditions can be dangerous.",
    emergencyNumber: "112 (General)",
    lastUpdated: new Date().toISOString(),
  },
  {
    name: "Netherlands",
    slug: "netherlands",
    code: "NL",
    capital: "Amsterdam",
    region: "Europe",
    subregion: "Western Europe",
    population: 17590000,
    area: 41850,
    languages: ["Dutch"],
    currencies: [{ name: "Euro", symbol: "€" }],
    timezones: ["UTC+01:00"],
    flag: "https://flagcdn.com/w640/nl.png",
    coatOfArms: "",
    image: "https://images.unsplash.com/photo-1534351590666-13e3e96b5017?w=800&q=80",
    borders: ["BEL", "DEU"],
    drivingSide: "right",
    callingCode: "+31",
    tld: ".nl",
    independent: true,
    unMember: true,
    landlocked: false,
    safetyRating: "very-high",
    visaInfo: "Schengen zone - 90-day visa-free for many nationalities.",
    bestTimeToVisit: "April-May for tulips and King's Day. June-August for warmest weather.",
    travelAdvisory: "Exercise normal precautions. Watch for bicycles. Very safe overall.",
    plugType: "Type C, Type F (230V)",
    waterSafety: "Tap water is safe and excellent quality.",
    healthInfo: "EHIC accepted for EU citizens. No special vaccinations required.",
    emergencyNumber: "112 (General)",
    lastUpdated: new Date().toISOString(),
  },
  {
    name: "Singapore",
    slug: "singapore",
    code: "SG",
    capital: "Singapore",
    region: "Asia",
    subregion: "South-Eastern Asia",
    population: 5454000,
    area: 710,
    languages: ["English", "Malay", "Mandarin", "Tamil"],
    currencies: [{ name: "Singapore dollar", symbol: "$" }],
    timezones: ["UTC+08:00"],
    flag: "https://flagcdn.com/w640/sg.png",
    coatOfArms: "",
    image: "https://images.unsplash.com/photo-1525625293386-3f8f99389edd?w=800&q=80",
    borders: [],
    drivingSide: "left",
    callingCode: "+65",
    tld: ".sg",
    independent: true,
    unMember: true,
    landlocked: false,
    safetyRating: "very-high",
    visaInfo: "Visa-free for 30-90 days for most nationalities. SG Arrival Card required.",
    bestTimeToVisit: "February-April (driest). Year-round destination with consistent tropical weather.",
    travelAdvisory: "Exercise normal precautions. One of the safest cities in the world. Strict laws on littering and drugs.",
    plugType: "Type G (230V)",
    waterSafety: "Tap water is safe and high quality.",
    healthInfo: "No mandatory vaccinations. Dengue fever risk - use insect repellent. Excellent healthcare.",
    emergencyNumber: "999 (Police), 995 (Fire/Ambulance)",
    lastUpdated: new Date().toISOString(),
  },
  {
    name: "Norway",
    slug: "norway",
    code: "NO",
    capital: "Oslo",
    region: "Europe",
    subregion: "Northern Europe",
    population: 5408000,
    area: 323802,
    languages: ["Norwegian"],
    currencies: [{ name: "Norwegian krone", symbol: "kr" }],
    timezones: ["UTC+01:00"],
    flag: "https://flagcdn.com/w640/no.png",
    coatOfArms: "",
    image: "https://images.unsplash.com/photo-1513519245088-0e12902e35ca?w=800&q=80",
    borders: ["FIN", "SWE", "RUS"],
    drivingSide: "right",
    callingCode: "+47",
    tld: ".no",
    independent: true,
    unMember: true,
    landlocked: false,
    safetyRating: "very-high",
    visaInfo: "Schengen zone - 90-day visa-free for many nationalities. Not an EU member.",
    bestTimeToVisit: "June-August for midnight sun and fjords. November-February for Northern Lights.",
    travelAdvisory: "Exercise normal precautions. Extremely safe. Very expensive country.",
    plugType: "Type C, Type F (230V)",
    waterSafety: "Tap water is safe and excellent quality everywhere.",
    healthInfo: "EHIC accepted for EU/EEA citizens. No special vaccinations required.",
    emergencyNumber: "112 (General), 110 (Fire), 113 (Ambulance)",
    lastUpdated: new Date().toISOString(),
  },
  {
    name: "Costa Rica",
    slug: "costa-rica",
    code: "CR",
    capital: "San Jose",
    region: "Americas",
    subregion: "Central America",
    population: 5180000,
    area: 51100,
    languages: ["Spanish"],
    currencies: [{ name: "Costa Rican colon", symbol: "₡" }],
    timezones: ["UTC-06:00"],
    flag: "https://flagcdn.com/w640/cr.png",
    coatOfArms: "",
    image: "https://images.unsplash.com/photo-1519999482648-25049ddd37b1?w=800&q=80",
    borders: ["NIC", "PAN"],
    drivingSide: "right",
    callingCode: "+506",
    tld: ".cr",
    independent: true,
    unMember: true,
    landlocked: false,
    safetyRating: "high",
    visaInfo: "Visa-free for up to 90 days for most Western nationalities.",
    bestTimeToVisit: "December-April (dry season). Green season (May-Nov) has fewer crowds and lower prices.",
    travelAdvisory: "Exercise normal precautions. Petty theft at beaches. Very tourist-friendly overall.",
    plugType: "Type A, Type B (120V)",
    waterSafety: "Tap water is safe in most areas. Use bottled water in remote regions.",
    healthInfo: "Routine vaccinations recommended. Mosquito repellent for dengue/Zika prevention.",
    emergencyNumber: "911 (General)",
    lastUpdated: new Date().toISOString(),
  },
  {
    name: "Kenya",
    slug: "kenya",
    code: "KE",
    capital: "Nairobi",
    region: "Africa",
    subregion: "Eastern Africa",
    population: 53770000,
    area: 580367,
    languages: ["Swahili", "English"],
    currencies: [{ name: "Kenyan shilling", symbol: "KSh" }],
    timezones: ["UTC+03:00"],
    flag: "https://flagcdn.com/w640/ke.png",
    coatOfArms: "",
    image: "https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=800&q=80",
    borders: ["ETH", "SOM", "SSD", "TZA", "UGA"],
    drivingSide: "left",
    callingCode: "+254",
    tld: ".ke",
    independent: true,
    unMember: true,
    landlocked: false,
    safetyRating: "moderate",
    visaInfo: "E-visa required for most nationalities. Apply online at evisa.go.ke before travel.",
    bestTimeToVisit: "July-October for Great Migration in Masai Mara. January-February also dry season.",
    travelAdvisory: "Exercise increased caution. Avoid border regions with Somalia. Tourist areas generally safe.",
    plugType: "Type G (240V)",
    waterSafety: "Do not drink tap water. Use bottled or purified water.",
    healthInfo: "Yellow fever vaccine required if arriving from endemic area. Malaria prophylaxis essential.",
    emergencyNumber: "999 (General), 112 (Mobile)",
    lastUpdated: new Date().toISOString(),
  },
  {
    name: "Croatia",
    slug: "croatia",
    code: "HR",
    capital: "Zagreb",
    region: "Europe",
    subregion: "Southeast Europe",
    population: 3888000,
    area: 56594,
    languages: ["Croatian"],
    currencies: [{ name: "Euro", symbol: "€" }],
    timezones: ["UTC+01:00"],
    flag: "https://flagcdn.com/w640/hr.png",
    coatOfArms: "",
    image: "https://images.unsplash.com/photo-1555990793-da11153b2473?w=800&q=80",
    borders: ["BIH", "HUN", "MNE", "SRB", "SVN"],
    drivingSide: "right",
    callingCode: "+385",
    tld: ".hr",
    independent: true,
    unMember: true,
    landlocked: false,
    safetyRating: "very-high",
    visaInfo: "Schengen zone since 2023 - 90-day visa-free for many nationalities.",
    bestTimeToVisit: "May-June and September for warm weather without peak crowds. July-August is busiest.",
    travelAdvisory: "Exercise normal precautions. Very safe country. Watch for landmines in remote border areas.",
    plugType: "Type C, Type F (230V)",
    waterSafety: "Tap water is safe to drink throughout the country.",
    healthInfo: "EHIC accepted for EU citizens. No special vaccinations required.",
    emergencyNumber: "112 (General)",
    lastUpdated: new Date().toISOString(),
  },
  {
    name: "Philippines",
    slug: "philippines",
    code: "PH",
    capital: "Manila",
    region: "Asia",
    subregion: "South-Eastern Asia",
    population: 113900000,
    area: 300000,
    languages: ["Filipino", "English"],
    currencies: [{ name: "Philippine peso", symbol: "₱" }],
    timezones: ["UTC+08:00"],
    flag: "https://flagcdn.com/w640/ph.png",
    coatOfArms: "",
    image: "https://images.unsplash.com/photo-1518509562904-e7ef99cdcc86?w=800&q=80",
    borders: [],
    drivingSide: "right",
    callingCode: "+63",
    tld: ".ph",
    independent: true,
    unMember: true,
    landlocked: false,
    safetyRating: "moderate",
    visaInfo: "Visa-free for 30 days for most nationalities. Extendable up to 36 months.",
    bestTimeToVisit: "November-May (dry season). December-February is peak season with coolest weather.",
    travelAdvisory: "Exercise increased caution. Avoid Mindanao and Sulu Archipelago. Tourist areas generally safe.",
    plugType: "Type A, Type B, Type C (220V)",
    waterSafety: "Do not drink tap water. Use bottled water.",
    healthInfo: "Hepatitis A and Typhoid vaccines recommended. Dengue risk - use insect repellent.",
    emergencyNumber: "911 (General)",
    lastUpdated: new Date().toISOString(),
  },
  {
    name: "Czech Republic",
    slug: "czech-republic",
    code: "CZ",
    capital: "Prague",
    region: "Europe",
    subregion: "Central Europe",
    population: 10700000,
    area: 78867,
    languages: ["Czech"],
    currencies: [{ name: "Czech koruna", symbol: "Kč" }],
    timezones: ["UTC+01:00"],
    flag: "https://flagcdn.com/w640/cz.png",
    coatOfArms: "",
    image: "https://images.unsplash.com/photo-1541849546-216549ae216d?w=800&q=80",
    borders: ["AUT", "DEU", "POL", "SVK"],
    drivingSide: "right",
    callingCode: "+420",
    tld: ".cz",
    independent: true,
    unMember: true,
    landlocked: true,
    safetyRating: "very-high",
    visaInfo: "Schengen zone - 90-day visa-free for many nationalities.",
    bestTimeToVisit: "April-June and September-October for mild weather and fewer tourists.",
    travelAdvisory: "Exercise normal precautions. Very safe. Watch for pickpockets in Prague tourist areas.",
    plugType: "Type C, Type E (230V)",
    waterSafety: "Tap water is safe to drink throughout the country.",
    healthInfo: "EHIC accepted for EU citizens. No special vaccinations required.",
    emergencyNumber: "112 (General), 158 (Police), 155 (Ambulance)",
    lastUpdated: new Date().toISOString(),
  },
  {
    name: "Chile",
    slug: "chile",
    code: "CL",
    capital: "Santiago",
    region: "Americas",
    subregion: "South America",
    population: 19490000,
    area: 756102,
    languages: ["Spanish"],
    currencies: [{ name: "Chilean peso", symbol: "$" }],
    timezones: ["UTC-06:00", "UTC-04:00", "UTC-03:00"],
    flag: "https://flagcdn.com/w640/cl.png",
    coatOfArms: "",
    image: "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=800&q=80",
    borders: ["ARG", "BOL", "PER"],
    drivingSide: "right",
    callingCode: "+56",
    tld: ".cl",
    independent: true,
    unMember: true,
    landlocked: false,
    safetyRating: "high",
    visaInfo: "Visa-free for up to 90 days for most Western nationalities.",
    bestTimeToVisit: "October-March for Patagonia and central Chile. June-September for skiing.",
    travelAdvisory: "Exercise normal precautions. One of the safest countries in South America.",
    plugType: "Type C, Type L (220V)",
    waterSafety: "Tap water is safe to drink in major cities.",
    healthInfo: "Routine vaccinations recommended. Altitude sickness possible in northern regions.",
    emergencyNumber: "131 (Ambulance), 132 (Fire), 133 (Police)",
    lastUpdated: new Date().toISOString(),
  },
  {
    name: "Tanzania",
    slug: "tanzania",
    code: "TZ",
    capital: "Dodoma",
    region: "Africa",
    subregion: "Eastern Africa",
    population: 61740000,
    area: 945087,
    languages: ["Swahili", "English"],
    currencies: [{ name: "Tanzanian shilling", symbol: "TSh" }],
    timezones: ["UTC+03:00"],
    flag: "https://flagcdn.com/w640/tz.png",
    coatOfArms: "",
    image: "https://images.unsplash.com/photo-1516426122078-c23e76319801?w=800&q=80",
    borders: ["BDI", "COD", "KEN", "MWI", "MOZ", "RWA", "UGA", "ZMB"],
    drivingSide: "left",
    callingCode: "+255",
    tld: ".tz",
    independent: true,
    unMember: true,
    landlocked: false,
    safetyRating: "moderate",
    visaInfo: "Visa required. E-visa available online. Visa on arrival for some nationalities ($50).",
    bestTimeToVisit: "June-October for dry season safaris. January-February for wildebeest calving in Serengeti.",
    travelAdvisory: "Exercise increased caution. Safari areas are safe with guides. Avoid isolated areas at night.",
    plugType: "Type D, Type G (230V)",
    waterSafety: "Do not drink tap water. Use bottled or purified water everywhere.",
    healthInfo: "Yellow fever vaccine required. Malaria prophylaxis essential. Typhoid and Hepatitis A recommended.",
    emergencyNumber: "112 (General), 114 (Police)",
    lastUpdated: new Date().toISOString(),
  },
  {
    name: "Austria",
    slug: "austria",
    code: "AT",
    capital: "Vienna",
    region: "Europe",
    subregion: "Central Europe",
    population: 9100000,
    area: 83871,
    languages: ["German"],
    currencies: [{ name: "Euro", symbol: "€" }],
    timezones: ["UTC+01:00"],
    flag: "https://flagcdn.com/w640/at.png",
    coatOfArms: "",
    image: "https://images.unsplash.com/photo-1516550893923-42d28e5677af?w=800&q=80",
    borders: ["CZE", "DEU", "HUN", "ITA", "LIE", "SVK", "SVN", "CHE"],
    drivingSide: "right",
    callingCode: "+43",
    tld: ".at",
    independent: true,
    unMember: true,
    landlocked: true,
    safetyRating: "very-high",
    visaInfo: "Schengen zone - 90-day visa-free for many nationalities.",
    bestTimeToVisit: "June-August for hiking and city tours. December-March for skiing and Christmas markets.",
    travelAdvisory: "Exercise normal precautions. Extremely safe country.",
    plugType: "Type C, Type F (230V)",
    waterSafety: "Tap water is excellent quality - some of the best in Europe.",
    healthInfo: "EHIC accepted for EU citizens. No special vaccinations required. World-class healthcare.",
    emergencyNumber: "112 (General), 133 (Police), 144 (Ambulance)",
    lastUpdated: new Date().toISOString(),
  },
  {
    name: "Malaysia",
    slug: "malaysia",
    code: "MY",
    capital: "Kuala Lumpur",
    region: "Asia",
    subregion: "South-Eastern Asia",
    population: 32770000,
    area: 330803,
    languages: ["Malay"],
    currencies: [{ name: "Malaysian ringgit", symbol: "RM" }],
    timezones: ["UTC+08:00"],
    flag: "https://flagcdn.com/w640/my.png",
    coatOfArms: "",
    image: "https://images.unsplash.com/photo-1596422846543-75c6fc197f07?w=800&q=80",
    borders: ["BRN", "IDN", "THA"],
    drivingSide: "left",
    callingCode: "+60",
    tld: ".my",
    independent: true,
    unMember: true,
    landlocked: false,
    safetyRating: "high",
    visaInfo: "Visa-free for 90 days for most nationalities. MDAC digital arrival card required.",
    bestTimeToVisit: "March-October for west coast. November-March for east coast. Year-round for KL.",
    travelAdvisory: "Exercise normal precautions. Generally safe. Respect Islamic customs in conservative areas.",
    plugType: "Type G (240V)",
    waterSafety: "Drink bottled water to be safe. Tap water is treated but not always reliable.",
    healthInfo: "Hepatitis A recommended. Dengue risk - use insect repellent. Excellent private healthcare.",
    emergencyNumber: "999 (General), 112 (Mobile)",
    lastUpdated: new Date().toISOString(),
  },
  {
    name: "Poland",
    slug: "poland",
    code: "PL",
    capital: "Warsaw",
    region: "Europe",
    subregion: "Central Europe",
    population: 37750000,
    area: 312696,
    languages: ["Polish"],
    currencies: [{ name: "Polish zloty", symbol: "zł" }],
    timezones: ["UTC+01:00"],
    flag: "https://flagcdn.com/w640/pl.png",
    coatOfArms: "",
    image: "https://images.unsplash.com/photo-1519197924294-4ba991a11128?w=800&q=80",
    borders: ["BLR", "CZE", "DEU", "LTU", "RUS", "SVK", "UKR"],
    drivingSide: "right",
    callingCode: "+48",
    tld: ".pl",
    independent: true,
    unMember: true,
    landlocked: false,
    safetyRating: "very-high",
    visaInfo: "Schengen zone - 90-day visa-free for many nationalities.",
    bestTimeToVisit: "May-September for warm weather. December for Christmas markets.",
    travelAdvisory: "Exercise normal precautions. Very safe country with low crime rates.",
    plugType: "Type C, Type E (230V)",
    waterSafety: "Tap water is safe to drink in major cities.",
    healthInfo: "EHIC accepted for EU citizens. No special vaccinations required.",
    emergencyNumber: "112 (General), 997 (Police), 999 (Ambulance)",
    lastUpdated: new Date().toISOString(),
  },
  {
    name: "Indonesia",
    slug: "indonesia",
    code: "ID",
    capital: "Jakarta",
    region: "Asia",
    subregion: "South-Eastern Asia",
    population: 273500000,
    area: 1904569,
    languages: ["Indonesian"],
    currencies: [{ name: "Indonesian rupiah", symbol: "Rp" }],
    timezones: ["UTC+07:00", "UTC+08:00", "UTC+09:00"],
    flag: "https://flagcdn.com/w640/id.png",
    coatOfArms: "",
    image: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800&q=80",
    borders: ["TLS", "MYS", "PNG"],
    drivingSide: "left",
    callingCode: "+62",
    tld: ".id",
    independent: true,
    unMember: true,
    landlocked: false,
    safetyRating: "moderate",
    visaInfo: "Visa on arrival (30 days, $35) for most nationalities. Extendable once for 30 more days.",
    bestTimeToVisit: "April-October (dry season). Bali is year-round but best May-September.",
    travelAdvisory: "Exercise normal precautions for Bali and major tourist areas. Increased caution elsewhere.",
    plugType: "Type C, Type F (230V)",
    waterSafety: "Do not drink tap water. Use bottled water everywhere.",
    healthInfo: "Hepatitis A, Typhoid recommended. Dengue risk. Malaria prophylaxis for remote islands.",
    emergencyNumber: "112 (General), 110 (Police), 118 (Ambulance)",
    lastUpdated: new Date().toISOString(),
  },
  {
    name: "United Arab Emirates",
    slug: "uae",
    code: "AE",
    capital: "Abu Dhabi",
    region: "Asia",
    subregion: "Western Asia",
    population: 9890000,
    area: 83600,
    languages: ["Arabic"],
    currencies: [{ name: "UAE dirham", symbol: "د.إ" }],
    timezones: ["UTC+04:00"],
    flag: "https://flagcdn.com/w640/ae.png",
    coatOfArms: "",
    image: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800&q=80",
    borders: ["OMN", "SAU"],
    drivingSide: "right",
    callingCode: "+971",
    tld: ".ae",
    independent: true,
    unMember: true,
    landlocked: false,
    safetyRating: "very-high",
    visaInfo: "Visa on arrival (30 days) for many Western nationalities. Others need pre-arranged visa.",
    bestTimeToVisit: "November-March for pleasant weather. Avoid June-August extreme heat (45°C+).",
    travelAdvisory: "Exercise normal precautions. Very safe. Strict laws on alcohol, dress code, and public behavior.",
    plugType: "Type G (220V)",
    waterSafety: "Tap water is desalinated and safe but most people drink bottled water.",
    healthInfo: "No mandatory vaccinations. Excellent healthcare facilities. Extreme heat risk in summer.",
    emergencyNumber: "999 (Police), 998 (Ambulance), 997 (Fire)",
    lastUpdated: new Date().toISOString(),
  },
  {
    name: "Sweden",
    slug: "sweden",
    code: "SE",
    capital: "Stockholm",
    region: "Europe",
    subregion: "Northern Europe",
    population: 10420000,
    area: 450295,
    languages: ["Swedish"],
    currencies: [{ name: "Swedish krona", symbol: "kr" }],
    timezones: ["UTC+01:00"],
    flag: "https://flagcdn.com/w640/se.png",
    coatOfArms: "",
    image: "https://images.unsplash.com/photo-1509356843151-3e7d96241e11?w=800&q=80",
    borders: ["FIN", "NOR"],
    drivingSide: "right",
    callingCode: "+46",
    tld: ".se",
    independent: true,
    unMember: true,
    landlocked: false,
    safetyRating: "very-high",
    visaInfo: "Schengen zone - 90-day visa-free for many nationalities.",
    bestTimeToVisit: "June-August for warmest weather and midnight sun. December-March for Northern Lights.",
    travelAdvisory: "Exercise normal precautions. Extremely safe country.",
    plugType: "Type C, Type F (230V)",
    waterSafety: "Tap water is excellent quality throughout the country.",
    healthInfo: "EHIC accepted for EU/EEA citizens. No special vaccinations required.",
    emergencyNumber: "112 (General)",
    lastUpdated: new Date().toISOString(),
  },
  {
    name: "Dominican Republic",
    slug: "dominican-republic",
    code: "DO",
    capital: "Santo Domingo",
    region: "Americas",
    subregion: "Caribbean",
    population: 10850000,
    area: 48671,
    languages: ["Spanish"],
    currencies: [{ name: "Dominican peso", symbol: "RD$" }],
    timezones: ["UTC-04:00"],
    flag: "https://flagcdn.com/w640/do.png",
    coatOfArms: "",
    image: "https://images.unsplash.com/photo-1569700903-28e7893d33e8?w=800&q=80",
    borders: ["HTI"],
    drivingSide: "right",
    callingCode: "+1-809",
    tld: ".do",
    independent: true,
    unMember: true,
    landlocked: false,
    safetyRating: "moderate",
    visaInfo: "Tourist card ($10) on arrival for most nationalities. Valid for 30 days.",
    bestTimeToVisit: "December-April for driest weather. June-November is hurricane season.",
    travelAdvisory: "Exercise increased caution. Stay in resort areas. Avoid driving at night.",
    plugType: "Type A, Type B (110V)",
    waterSafety: "Do not drink tap water. Use bottled water.",
    healthInfo: "Hepatitis A and Typhoid recommended. Dengue risk - use insect repellent.",
    emergencyNumber: "911 (General)",
    lastUpdated: new Date().toISOString(),
  },
  {
    name: "Ireland",
    slug: "ireland",
    code: "IE",
    capital: "Dublin",
    region: "Europe",
    subregion: "Northern Europe",
    population: 5030000,
    area: 70273,
    languages: ["Irish", "English"],
    currencies: [{ name: "Euro", symbol: "€" }],
    timezones: ["UTC+00:00"],
    flag: "https://flagcdn.com/w640/ie.png",
    coatOfArms: "",
    image: "https://images.unsplash.com/photo-1590089415225-401ed6f9db8e?w=800&q=80",
    borders: ["GBR"],
    drivingSide: "left",
    callingCode: "+353",
    tld: ".ie",
    independent: true,
    unMember: true,
    landlocked: false,
    safetyRating: "very-high",
    visaInfo: "Visa-free for up to 90 days for most Western nationalities. EU citizens have free movement.",
    bestTimeToVisit: "May-September for warmest and driest weather. March for St. Patrick's Day.",
    travelAdvisory: "Exercise normal precautions. Very safe and friendly country.",
    plugType: "Type G (230V)",
    waterSafety: "Tap water is safe to drink throughout the country.",
    healthInfo: "EHIC accepted for EU citizens. No special vaccinations required.",
    emergencyNumber: "112 or 999 (General)",
    lastUpdated: new Date().toISOString(),
  },
  {
    name: "Cuba",
    slug: "cuba",
    code: "CU",
    capital: "Havana",
    region: "Americas",
    subregion: "Caribbean",
    population: 11330000,
    area: 109884,
    languages: ["Spanish"],
    currencies: [{ name: "Cuban peso", symbol: "$" }],
    timezones: ["UTC-05:00"],
    flag: "https://flagcdn.com/w640/cu.png",
    coatOfArms: "",
    image: "https://images.unsplash.com/photo-1500759285222-a95626b934cb?w=800&q=80",
    borders: [],
    drivingSide: "right",
    callingCode: "+53",
    tld: ".cu",
    independent: true,
    unMember: true,
    landlocked: false,
    safetyRating: "high",
    visaInfo: "Tourist visa (tarjeta de turista) required. Available from airlines or embassies. US citizens have restrictions.",
    bestTimeToVisit: "November-April for dry season and cooler temperatures.",
    travelAdvisory: "Exercise increased caution. Generally safe for tourists. Limited internet and banking infrastructure.",
    plugType: "Type A, Type B, Type C (110/220V)",
    waterSafety: "Do not drink tap water. Use bottled water.",
    healthInfo: "Hepatitis A and Typhoid recommended. Bring personal medications as pharmacies have limited stock.",
    emergencyNumber: "106 (Police), 104 (Ambulance), 105 (Fire)",
    lastUpdated: new Date().toISOString(),
  },
];

export function getCountryBySlug(slug: string): Country | undefined {
  return countriesData.find((c) => c.slug === slug);
}

export function getCountriesByRegion(region: string): Country[] {
  return countriesData.filter((c) => c.region === region);
}

export function searchCountries(query: string): Country[] {
  const q = query.toLowerCase();
  return countriesData.filter(
    (c) =>
      c.name.toLowerCase().includes(q) ||
      c.capital.toLowerCase().includes(q) ||
      c.region.toLowerCase().includes(q)
  );
}
