import { USState } from "./types";

export const statesData: USState[] = [
  {
    name: "California",
    slug: "california",
    abbreviation: "CA",
    capital: "Sacramento",
    population: 39538223,
    area: 163696,
    region: "West",
    nickname: "The Golden State",
    motto: "Eureka",
    bird: "California Quail",
    flower: "California Poppy",
    tree: "Coast Redwood",
    statehood: "September 9, 1850 (31st state)",
    image: "https://images.unsplash.com/photo-1449034446853-66c86144b0ad?w=800&q=80",
    flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Flag_of_California.svg/640px-Flag_of_California.svg.png",
    timezone: "Pacific (UTC-8)",
    majorCities: ["Los Angeles", "San Francisco", "San Diego", "San Jose", "Sacramento"],
    topAttractions: ["Yosemite National Park", "Golden Gate Bridge", "Disneyland", "Hollywood", "Big Sur"],
    climate: "Mediterranean climate along coast; desert in southeast; alpine in mountains",
    bestTimeToVisit: "September-November for warm weather without summer crowds",
    avgTemperature: { summer: "75-90°F (24-32°C)", winter: "45-65°F (7-18°C)" },
    costOfLiving: "very-high",
    safetyRating: "high",
    funFact: "If California were a country, it would have the 5th largest economy in the world.",
    lastUpdated: new Date().toISOString(),
  },
  {
    name: "New York",
    slug: "new-york",
    abbreviation: "NY",
    capital: "Albany",
    population: 20201249,
    area: 54555,
    region: "Northeast",
    nickname: "The Empire State",
    motto: "Excelsior (Ever Upward)",
    bird: "Eastern Bluebird",
    flower: "Rose",
    tree: "Sugar Maple",
    statehood: "July 26, 1788 (11th state)",
    image: "https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?w=800&q=80",
    flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Flag_of_New_York.svg/640px-Flag_of_New_York.svg.png",
    timezone: "Eastern (UTC-5)",
    majorCities: ["New York City", "Buffalo", "Rochester", "Syracuse", "Albany"],
    topAttractions: ["Statue of Liberty", "Central Park", "Niagara Falls", "Times Square", "Brooklyn Bridge"],
    climate: "Humid continental with warm summers and cold, snowy winters",
    bestTimeToVisit: "April-June and September-November for mild weather",
    avgTemperature: { summer: "70-85°F (21-29°C)", winter: "25-40°F (-4-4°C)" },
    costOfLiving: "very-high",
    safetyRating: "high",
    funFact: "New York City's subway system has 472 stations, the most of any system in the world.",
    lastUpdated: new Date().toISOString(),
  },
  {
    name: "Texas",
    slug: "texas",
    abbreviation: "TX",
    capital: "Austin",
    population: 29145505,
    area: 268596,
    region: "South",
    nickname: "The Lone Star State",
    motto: "Friendship",
    bird: "Northern Mockingbird",
    flower: "Bluebonnet",
    tree: "Pecan",
    statehood: "December 29, 1845 (28th state)",
    image: "https://images.unsplash.com/photo-1531218150217-54595bc2b934?w=800&q=80",
    flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/Flag_of_Texas.svg/640px-Flag_of_Texas.svg.png",
    timezone: "Central (UTC-6)",
    majorCities: ["Houston", "Dallas", "San Antonio", "Austin", "Fort Worth"],
    topAttractions: ["The Alamo", "Big Bend National Park", "River Walk", "Space Center Houston", "Padre Island"],
    climate: "Varies from humid subtropical in east to arid in west",
    bestTimeToVisit: "March-May and October-November for comfortable temperatures",
    avgTemperature: { summer: "85-100°F (29-38°C)", winter: "40-60°F (4-16°C)" },
    costOfLiving: "moderate",
    safetyRating: "high",
    funFact: "Texas is the only state to have the flags of 6 different nations fly over it.",
    lastUpdated: new Date().toISOString(),
  },
  {
    name: "Florida",
    slug: "florida",
    abbreviation: "FL",
    capital: "Tallahassee",
    population: 21538187,
    area: 65758,
    region: "South",
    nickname: "The Sunshine State",
    motto: "In God We Trust",
    bird: "Northern Mockingbird",
    flower: "Orange Blossom",
    tree: "Sabal Palm",
    statehood: "March 3, 1845 (27th state)",
    image: "https://images.unsplash.com/photo-1535498730771-e735b998cd64?w=800&q=80",
    flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/Flag_of_Florida.svg/640px-Flag_of_Florida.svg.png",
    timezone: "Eastern (UTC-5)",
    majorCities: ["Miami", "Orlando", "Tampa", "Jacksonville", "Fort Lauderdale"],
    topAttractions: ["Walt Disney World", "Everglades National Park", "Kennedy Space Center", "South Beach", "Key West"],
    climate: "Tropical and subtropical with hot, humid summers and mild winters",
    bestTimeToVisit: "November-April for pleasant weather. Avoid hurricane season (June-November).",
    avgTemperature: { summer: "80-95°F (27-35°C)", winter: "55-75°F (13-24°C)" },
    costOfLiving: "moderate",
    safetyRating: "high",
    funFact: "Florida has more golf courses than any other state in the US.",
    lastUpdated: new Date().toISOString(),
  },
  {
    name: "Hawaii",
    slug: "hawaii",
    abbreviation: "HI",
    capital: "Honolulu",
    population: 1455271,
    area: 10932,
    region: "West",
    nickname: "The Aloha State",
    motto: "Ua Mau ke Ea o ka Aina i ka Pono",
    bird: "Nēnē (Hawaiian Goose)",
    flower: "Yellow Hibiscus",
    tree: "Candlenut",
    statehood: "August 21, 1959 (50th state)",
    image: "https://images.unsplash.com/photo-1507876466758-bc54f384809c?w=800&q=80",
    flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Flag_of_Hawaii.svg/640px-Flag_of_Hawaii.svg.png",
    timezone: "Hawaii-Aleutian (UTC-10)",
    majorCities: ["Honolulu", "Hilo", "Kailua", "Kapolei", "Pearl City"],
    topAttractions: ["Waikiki Beach", "Pearl Harbor", "Haleakala National Park", "Na Pali Coast", "Volcanoes National Park"],
    climate: "Tropical with warm temperatures year-round and trade winds",
    bestTimeToVisit: "April-June and September-November for fewer crowds and great weather",
    avgTemperature: { summer: "80-88°F (27-31°C)", winter: "70-80°F (21-27°C)" },
    costOfLiving: "very-high",
    safetyRating: "very-high",
    funFact: "Hawaii is the only US state that grows coffee commercially.",
    lastUpdated: new Date().toISOString(),
  },
  {
    name: "Colorado",
    slug: "colorado",
    abbreviation: "CO",
    capital: "Denver",
    population: 5773714,
    area: 104094,
    region: "West",
    nickname: "The Centennial State",
    motto: "Nil Sine Numine (Nothing Without Providence)",
    bird: "Lark Bunting",
    flower: "Rocky Mountain Columbine",
    tree: "Colorado Blue Spruce",
    statehood: "August 1, 1876 (38th state)",
    image: "https://images.unsplash.com/photo-1546156929-a4c0ac411f47?w=800&q=80",
    flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/Flag_of_Colorado.svg/640px-Flag_of_Colorado.svg.png",
    timezone: "Mountain (UTC-7)",
    majorCities: ["Denver", "Colorado Springs", "Aurora", "Fort Collins", "Boulder"],
    topAttractions: ["Rocky Mountain National Park", "Garden of the Gods", "Mesa Verde", "Aspen Ski Resort", "Red Rocks Amphitheatre"],
    climate: "Semi-arid continental with cold winters and warm summers; varies greatly with altitude",
    bestTimeToVisit: "June-August for hiking; December-March for skiing",
    avgTemperature: { summer: "70-90°F (21-32°C)", winter: "20-45°F (-7-7°C)" },
    costOfLiving: "high",
    safetyRating: "high",
    funFact: "Colorado has 58 mountain peaks over 14,000 feet, known as 'fourteeners.'",
    lastUpdated: new Date().toISOString(),
  },
  {
    name: "Washington",
    slug: "washington",
    abbreviation: "WA",
    capital: "Olympia",
    population: 7614893,
    area: 71298,
    region: "West",
    nickname: "The Evergreen State",
    motto: "Al-ki (By and By)",
    bird: "Willow Goldfinch",
    flower: "Coast Rhododendron",
    tree: "Western Hemlock",
    statehood: "November 11, 1889 (42nd state)",
    image: "https://images.unsplash.com/photo-1516905041604-7935af78f572?w=800&q=80",
    flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/Flag_of_Washington.svg/640px-Flag_of_Washington.svg.png",
    timezone: "Pacific (UTC-8)",
    majorCities: ["Seattle", "Spokane", "Tacoma", "Vancouver", "Bellevue"],
    topAttractions: ["Mount Rainier", "Pike Place Market", "Olympic National Park", "Space Needle", "San Juan Islands"],
    climate: "Oceanic west of Cascades; semi-arid in east. Rainy winters, dry summers.",
    bestTimeToVisit: "June-September for dry and warm weather",
    avgTemperature: { summer: "65-80°F (18-27°C)", winter: "35-45°F (2-7°C)" },
    costOfLiving: "high",
    safetyRating: "high",
    funFact: "Washington produces more apples than any other state in the US.",
    lastUpdated: new Date().toISOString(),
  },
  {
    name: "Massachusetts",
    slug: "massachusetts",
    abbreviation: "MA",
    capital: "Boston",
    population: 7029917,
    area: 10554,
    region: "Northeast",
    nickname: "The Bay State",
    motto: "Ense Petit Placidam Sub Libertate Quietem",
    bird: "Black-capped Chickadee",
    flower: "Mayflower",
    tree: "American Elm",
    statehood: "February 6, 1788 (6th state)",
    image: "https://images.unsplash.com/photo-1501979376754-1d1e0631dc2c?w=800&q=80",
    flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Flag_of_Massachusetts.svg/640px-Flag_of_Massachusetts.svg.png",
    timezone: "Eastern (UTC-5)",
    majorCities: ["Boston", "Worcester", "Springfield", "Cambridge", "Lowell"],
    topAttractions: ["Freedom Trail", "Cape Cod", "Martha's Vineyard", "Harvard University", "Fenway Park"],
    climate: "Humid continental with warm summers and cold, snowy winters",
    bestTimeToVisit: "September-October for fall foliage; June-August for beaches",
    avgTemperature: { summer: "70-82°F (21-28°C)", winter: "22-38°F (-6-3°C)" },
    costOfLiving: "very-high",
    safetyRating: "high",
    funFact: "Harvard, founded in 1636, is the oldest institution of higher education in the US.",
    lastUpdated: new Date().toISOString(),
  },
  {
    name: "Arizona",
    slug: "arizona",
    abbreviation: "AZ",
    capital: "Phoenix",
    population: 7151502,
    area: 113990,
    region: "West",
    nickname: "The Grand Canyon State",
    motto: "Ditat Deus (God Enriches)",
    bird: "Cactus Wren",
    flower: "Saguaro Cactus Blossom",
    tree: "Palo Verde",
    statehood: "February 14, 1912 (48th state)",
    image: "https://images.unsplash.com/photo-1474044159687-1ee9f3a51722?w=800&q=80",
    flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Flag_of_Arizona.svg/640px-Flag_of_Arizona.svg.png",
    timezone: "Mountain (UTC-7, no DST)",
    majorCities: ["Phoenix", "Tucson", "Mesa", "Scottsdale", "Chandler"],
    topAttractions: ["Grand Canyon", "Sedona Red Rocks", "Monument Valley", "Antelope Canyon", "Saguaro National Park"],
    climate: "Arid desert in south; semi-arid plateau in north with cooler temperatures",
    bestTimeToVisit: "October-April for comfortable temperatures. Summer is extremely hot.",
    avgTemperature: { summer: "95-115°F (35-46°C)", winter: "45-70°F (7-21°C)" },
    costOfLiving: "moderate",
    safetyRating: "high",
    funFact: "The Grand Canyon is 277 miles long, up to 18 miles wide, and over a mile deep.",
    lastUpdated: new Date().toISOString(),
  },
  {
    name: "Oregon",
    slug: "oregon",
    abbreviation: "OR",
    capital: "Salem",
    population: 4237256,
    area: 98379,
    region: "West",
    nickname: "The Beaver State",
    motto: "She Flies with Her Own Wings",
    bird: "Western Meadowlark",
    flower: "Oregon Grape",
    tree: "Douglas Fir",
    statehood: "February 14, 1859 (33rd state)",
    image: "https://images.unsplash.com/photo-1541029071515-84cc54f84dc5?w=800&q=80",
    flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Flag_of_Oregon.svg/640px-Flag_of_Oregon.svg.png",
    timezone: "Pacific (UTC-8)",
    majorCities: ["Portland", "Salem", "Eugene", "Bend", "Medford"],
    topAttractions: ["Crater Lake", "Multnomah Falls", "Columbia River Gorge", "Cannon Beach", "Mt. Hood"],
    climate: "Oceanic west; semi-arid east. Rainy winters, dry summers on the coast.",
    bestTimeToVisit: "June-September for dry weather and outdoor activities",
    avgTemperature: { summer: "65-85°F (18-29°C)", winter: "35-48°F (2-9°C)" },
    costOfLiving: "high",
    safetyRating: "high",
    funFact: "Oregon has no sales tax, making it a shopper's paradise.",
    lastUpdated: new Date().toISOString(),
  },
  {
    name: "Tennessee",
    slug: "tennessee",
    abbreviation: "TN",
    capital: "Nashville",
    population: 6910840,
    area: 42144,
    region: "South",
    nickname: "The Volunteer State",
    motto: "Agriculture and Commerce",
    bird: "Northern Mockingbird",
    flower: "Iris",
    tree: "Tulip Poplar",
    statehood: "June 1, 1796 (16th state)",
    image: "https://images.unsplash.com/photo-1545419913-775e4b1f1511?w=800&q=80",
    flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Flag_of_Tennessee.svg/640px-Flag_of_Tennessee.svg.png",
    timezone: "Central/Eastern (UTC-6/UTC-5)",
    majorCities: ["Nashville", "Memphis", "Knoxville", "Chattanooga", "Clarksville"],
    topAttractions: ["Great Smoky Mountains", "Grand Ole Opry", "Graceland", "Beale Street", "Dollywood"],
    climate: "Humid subtropical with hot summers and mild to cool winters",
    bestTimeToVisit: "April-May and September-November for mild weather and festivals",
    avgTemperature: { summer: "80-92°F (27-33°C)", winter: "30-50°F (-1-10°C)" },
    costOfLiving: "low",
    safetyRating: "high",
    funFact: "Nashville is known as 'Music City' and is the birthplace of country music.",
    lastUpdated: new Date().toISOString(),
  },
  {
    name: "Montana",
    slug: "montana",
    abbreviation: "MT",
    capital: "Helena",
    population: 1084225,
    area: 147040,
    region: "West",
    nickname: "The Treasure State",
    motto: "Oro y Plata (Gold and Silver)",
    bird: "Western Meadowlark",
    flower: "Bitterroot",
    tree: "Ponderosa Pine",
    statehood: "November 8, 1889 (41st state)",
    image: "https://images.unsplash.com/photo-1508193638397-1c4234db14d8?w=800&q=80",
    flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Flag_of_Montana.svg/640px-Flag_of_Montana.svg.png",
    timezone: "Mountain (UTC-7)",
    majorCities: ["Billings", "Missoula", "Great Falls", "Bozeman", "Helena"],
    topAttractions: ["Glacier National Park", "Yellowstone (Montana entrance)", "Big Sky Resort", "Flathead Lake", "Beartooth Highway"],
    climate: "Continental with cold winters and warm summers; highly variable weather",
    bestTimeToVisit: "June-September for warm weather and national park access",
    avgTemperature: { summer: "65-85°F (18-29°C)", winter: "10-32°F (-12-0°C)" },
    costOfLiving: "moderate",
    safetyRating: "very-high",
    funFact: "Montana has more cattle than people - about 2.6 million cows to 1.1 million people.",
    lastUpdated: new Date().toISOString(),
  },
  {
    name: "Georgia",
    slug: "georgia-state",
    abbreviation: "GA",
    capital: "Atlanta",
    population: 10711908,
    area: 59425,
    region: "South",
    nickname: "The Peach State",
    motto: "Wisdom, Justice, and Moderation",
    bird: "Brown Thrasher",
    flower: "Cherokee Rose",
    tree: "Live Oak",
    statehood: "January 2, 1788 (4th state)",
    image: "https://images.unsplash.com/photo-1575917649705-5b59aaa12e6b?w=800&q=80",
    flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/Flag_of_Georgia_%28U.S._state%29.svg/640px-Flag_of_Georgia_%28U.S._state%29.svg.png",
    timezone: "Eastern (UTC-5)",
    majorCities: ["Atlanta", "Augusta", "Savannah", "Columbus", "Athens"],
    topAttractions: ["Savannah Historic District", "Georgia Aquarium", "Stone Mountain", "Okefenokee Swamp", "Tybee Island"],
    climate: "Humid subtropical with hot summers and mild winters",
    bestTimeToVisit: "March-May and September-November for pleasant weather",
    avgTemperature: { summer: "80-92°F (27-33°C)", winter: "35-55°F (2-13°C)" },
    costOfLiving: "moderate",
    safetyRating: "high",
    funFact: "Georgia is actually the largest state east of the Mississippi River.",
    lastUpdated: new Date().toISOString(),
  },
  {
    name: "Nevada",
    slug: "nevada",
    abbreviation: "NV",
    capital: "Carson City",
    population: 3104614,
    area: 110572,
    region: "West",
    nickname: "The Silver State",
    motto: "All for Our Country",
    bird: "Mountain Bluebird",
    flower: "Sagebrush",
    tree: "Bristlecone Pine",
    statehood: "October 31, 1864 (36th state)",
    image: "https://images.unsplash.com/photo-1581351721010-8cf859cb14a4?w=800&q=80",
    flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/Flag_of_Nevada.svg/640px-Flag_of_Nevada.svg.png",
    timezone: "Pacific (UTC-8)",
    majorCities: ["Las Vegas", "Reno", "Henderson", "North Las Vegas", "Sparks"],
    topAttractions: ["Las Vegas Strip", "Red Rock Canyon", "Lake Tahoe", "Valley of Fire", "Hoover Dam"],
    climate: "Arid desert with hot summers and mild winters; cooler in northern Nevada",
    bestTimeToVisit: "March-May and September-November for comfortable temperatures",
    avgTemperature: { summer: "90-110°F (32-43°C)", winter: "35-55°F (2-13°C)" },
    costOfLiving: "moderate",
    safetyRating: "high",
    funFact: "Nevada is the driest state in the US, receiving an average of only 9.5 inches of rainfall annually.",
    lastUpdated: new Date().toISOString(),
  },
  {
    name: "Alaska",
    slug: "alaska",
    abbreviation: "AK",
    capital: "Juneau",
    population: 733391,
    area: 665384,
    region: "West",
    nickname: "The Last Frontier",
    motto: "North to the Future",
    bird: "Willow Ptarmigan",
    flower: "Forget-Me-Not",
    tree: "Sitka Spruce",
    statehood: "January 3, 1959 (49th state)",
    image: "https://images.unsplash.com/photo-1531176175280-109afb2f4e12?w=800&q=80",
    flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Flag_of_Alaska.svg/640px-Flag_of_Alaska.svg.png",
    timezone: "Alaska (UTC-9)",
    majorCities: ["Anchorage", "Fairbanks", "Juneau", "Sitka", "Ketchikan"],
    topAttractions: ["Denali National Park", "Glacier Bay", "Northern Lights", "Kenai Fjords", "Inside Passage"],
    climate: "Subarctic to arctic. Long, cold winters and short, cool summers. Extreme daylight variations.",
    bestTimeToVisit: "June-August for warmest weather and long daylight hours",
    avgTemperature: { summer: "55-70°F (13-21°C)", winter: "-10-25°F (-23--4°C)" },
    costOfLiving: "high",
    safetyRating: "high",
    funFact: "Alaska is so big that if it were cut in half, the two pieces would still be the two largest US states.",
    lastUpdated: new Date().toISOString(),
  },
  {
    name: "Illinois",
    slug: "illinois",
    abbreviation: "IL",
    capital: "Springfield",
    population: 12812508,
    area: 57914,
    region: "Midwest",
    nickname: "The Prairie State",
    motto: "State Sovereignty, National Union",
    bird: "Northern Cardinal",
    flower: "Violet",
    tree: "White Oak",
    statehood: "December 3, 1818 (21st state)",
    image: "https://images.unsplash.com/photo-1494522855154-9297ac14b55f?w=800&q=80",
    flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Flag_of_Illinois.svg/640px-Flag_of_Illinois.svg.png",
    timezone: "Central (UTC-6)",
    majorCities: ["Chicago", "Aurora", "Naperville", "Springfield", "Rockford"],
    topAttractions: ["Millennium Park", "Willis Tower", "Navy Pier", "Starved Rock State Park", "Art Institute of Chicago"],
    climate: "Humid continental with hot summers and cold, snowy winters",
    bestTimeToVisit: "April-June and September-October for pleasant weather",
    avgTemperature: { summer: "75-88°F (24-31°C)", winter: "20-35°F (-7-2°C)" },
    costOfLiving: "moderate",
    safetyRating: "high",
    funFact: "Chicago's nickname 'The Windy City' actually refers to boastful politicians, not the weather.",
    lastUpdated: new Date().toISOString(),
  },
  {
    name: "Pennsylvania",
    slug: "pennsylvania",
    abbreviation: "PA",
    capital: "Harrisburg",
    population: 13002700,
    area: 46054,
    region: "Northeast",
    nickname: "The Keystone State",
    motto: "Virtue, Liberty and Independence",
    bird: "Ruffed Grouse",
    flower: "Mountain Laurel",
    tree: "Eastern Hemlock",
    statehood: "December 12, 1787 (2nd state)",
    image: "https://images.unsplash.com/photo-1569761316261-9a8696fa2ca3?w=800&q=80",
    flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/Flag_of_Pennsylvania.svg/640px-Flag_of_Pennsylvania.svg.png",
    timezone: "Eastern (UTC-5)",
    majorCities: ["Philadelphia", "Pittsburgh", "Allentown", "Erie", "Harrisburg"],
    topAttractions: ["Independence Hall", "Liberty Bell", "Gettysburg", "Hersheypark", "Pocono Mountains"],
    climate: "Humid continental with warm summers and cold winters",
    bestTimeToVisit: "May-June and September-October for mild weather and fall foliage",
    avgTemperature: { summer: "72-85°F (22-29°C)", winter: "24-38°F (-4-3°C)" },
    costOfLiving: "moderate",
    safetyRating: "high",
    funFact: "The first computer (ENIAC) was built at the University of Pennsylvania in 1946.",
    lastUpdated: new Date().toISOString(),
  },
  {
    name: "Ohio",
    slug: "ohio",
    abbreviation: "OH",
    capital: "Columbus",
    population: 11799448,
    area: 44826,
    region: "Midwest",
    nickname: "The Buckeye State",
    motto: "With God, All Things Are Possible",
    bird: "Northern Cardinal",
    flower: "Scarlet Carnation",
    tree: "Ohio Buckeye",
    statehood: "March 1, 1803 (17th state)",
    image: "https://images.unsplash.com/photo-1570168007204-dfb528c6958f?w=800&q=80",
    flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Flag_of_Ohio.svg/640px-Flag_of_Ohio.svg.png",
    timezone: "Eastern (UTC-5)",
    majorCities: ["Columbus", "Cleveland", "Cincinnati", "Toledo", "Akron"],
    topAttractions: ["Rock & Roll Hall of Fame", "Hocking Hills", "Cedar Point", "Cincinnati Zoo", "Amish Country"],
    climate: "Humid continental with warm summers and cold winters",
    bestTimeToVisit: "May-June and September-October for comfortable weather",
    avgTemperature: { summer: "72-85°F (22-29°C)", winter: "22-36°F (-6-2°C)" },
    costOfLiving: "low",
    safetyRating: "high",
    funFact: "Ohio has produced more US Presidents (8) than any other state.",
    lastUpdated: new Date().toISOString(),
  },
  {
    name: "Michigan",
    slug: "michigan",
    abbreviation: "MI",
    capital: "Lansing",
    population: 10077331,
    area: 96714,
    region: "Midwest",
    nickname: "The Great Lakes State",
    motto: "Si Quaeris Peninsulam Amoenam Circumspice",
    bird: "American Robin",
    flower: "Apple Blossom",
    tree: "White Pine",
    statehood: "January 26, 1837 (26th state)",
    image: "https://images.unsplash.com/photo-1562095241-8c6714fd4178?w=800&q=80",
    flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Flag_of_Michigan.svg/640px-Flag_of_Michigan.svg.png",
    timezone: "Eastern (UTC-5)",
    majorCities: ["Detroit", "Grand Rapids", "Ann Arbor", "Lansing", "Traverse City"],
    topAttractions: ["Sleeping Bear Dunes", "Mackinac Island", "Henry Ford Museum", "Pictured Rocks", "Isle Royale"],
    climate: "Humid continental with warm summers and cold, snowy winters; lake effect snow",
    bestTimeToVisit: "June-August for summer activities; October for fall colors",
    avgTemperature: { summer: "70-83°F (21-28°C)", winter: "18-32°F (-8-0°C)" },
    costOfLiving: "moderate",
    safetyRating: "high",
    funFact: "Michigan has more coastline than any state except Alaska, thanks to the Great Lakes.",
    lastUpdated: new Date().toISOString(),
  },
  {
    name: "North Carolina",
    slug: "north-carolina",
    abbreviation: "NC",
    capital: "Raleigh",
    population: 10439388,
    area: 53819,
    region: "South",
    nickname: "The Tar Heel State",
    motto: "Esse Quam Videri (To Be Rather Than to Seem)",
    bird: "Northern Cardinal",
    flower: "Dogwood",
    tree: "Pine",
    statehood: "November 21, 1789 (12th state)",
    image: "https://images.unsplash.com/photo-1564604561904-96fc6f7dbb8f?w=800&q=80",
    flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Flag_of_North_Carolina.svg/640px-Flag_of_North_Carolina.svg.png",
    timezone: "Eastern (UTC-5)",
    majorCities: ["Charlotte", "Raleigh", "Greensboro", "Durham", "Asheville"],
    topAttractions: ["Blue Ridge Parkway", "Great Smoky Mountains", "Outer Banks", "Biltmore Estate", "Wright Brothers Memorial"],
    climate: "Humid subtropical with hot summers; cooler in the mountains",
    bestTimeToVisit: "April-May and September-November for mild weather",
    avgTemperature: { summer: "78-90°F (26-32°C)", winter: "33-52°F (1-11°C)" },
    costOfLiving: "moderate",
    safetyRating: "high",
    funFact: "The Wright Brothers made the first powered flight at Kitty Hawk, North Carolina in 1903.",
    lastUpdated: new Date().toISOString(),
  },
  {
    name: "Virginia",
    slug: "virginia",
    abbreviation: "VA",
    capital: "Richmond",
    population: 8631393,
    area: 42775,
    region: "South",
    nickname: "The Old Dominion",
    motto: "Sic Semper Tyrannis (Thus Always to Tyrants)",
    bird: "Northern Cardinal",
    flower: "American Dogwood",
    tree: "Flowering Dogwood",
    statehood: "June 25, 1788 (10th state)",
    image: "https://images.unsplash.com/photo-1558470598-a5dda9640f68?w=800&q=80",
    flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Flag_of_Virginia.svg/640px-Flag_of_Virginia.svg.png",
    timezone: "Eastern (UTC-5)",
    majorCities: ["Virginia Beach", "Norfolk", "Richmond", "Arlington", "Alexandria"],
    topAttractions: ["Shenandoah National Park", "Colonial Williamsburg", "Arlington Cemetery", "Virginia Beach", "Luray Caverns"],
    climate: "Humid subtropical with hot summers and mild winters",
    bestTimeToVisit: "April-June and September-November for pleasant weather",
    avgTemperature: { summer: "78-90°F (26-32°C)", winter: "30-48°F (-1-9°C)" },
    costOfLiving: "high",
    safetyRating: "high",
    funFact: "Eight US Presidents were born in Virginia — more than any other state.",
    lastUpdated: new Date().toISOString(),
  },
  {
    name: "Minnesota",
    slug: "minnesota",
    abbreviation: "MN",
    capital: "Saint Paul",
    population: 5706494,
    area: 86936,
    region: "Midwest",
    nickname: "The North Star State",
    motto: "L'Etoile du Nord (The Star of the North)",
    bird: "Common Loon",
    flower: "Pink and White Lady's Slipper",
    tree: "Red Pine",
    statehood: "May 11, 1858 (32nd state)",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=800&q=80",
    flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Flag_of_Minnesota.svg/640px-Flag_of_Minnesota.svg.png",
    timezone: "Central (UTC-6)",
    majorCities: ["Minneapolis", "Saint Paul", "Rochester", "Duluth", "Bloomington"],
    topAttractions: ["Boundary Waters", "Mall of America", "Minnehaha Falls", "North Shore", "Voyageurs National Park"],
    climate: "Humid continental with warm summers and very cold winters",
    bestTimeToVisit: "June-August for warm weather and lakes; January-February for winter sports",
    avgTemperature: { summer: "70-85°F (21-29°C)", winter: "5-25°F (-15--4°C)" },
    costOfLiving: "moderate",
    safetyRating: "high",
    funFact: "Minnesota has 11,842 lakes — the most of any state. The nickname 'Land of 10,000 Lakes' actually undercounts.",
    lastUpdated: new Date().toISOString(),
  },
  {
    name: "Wisconsin",
    slug: "wisconsin",
    abbreviation: "WI",
    capital: "Madison",
    population: 5893718,
    area: 65496,
    region: "Midwest",
    nickname: "America's Dairyland",
    motto: "Forward",
    bird: "American Robin",
    flower: "Wood Violet",
    tree: "Sugar Maple",
    statehood: "May 29, 1848 (30th state)",
    image: "https://images.unsplash.com/photo-1569163139599-0f4517e36f51?w=800&q=80",
    flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Flag_of_Wisconsin.svg/640px-Flag_of_Wisconsin.svg.png",
    timezone: "Central (UTC-6)",
    majorCities: ["Milwaukee", "Madison", "Green Bay", "Kenosha", "Racine"],
    topAttractions: ["Wisconsin Dells", "Apostle Islands", "Door County", "Lambeau Field", "Devil's Lake State Park"],
    climate: "Humid continental with warm summers and very cold, snowy winters",
    bestTimeToVisit: "June-August for summer activities; September-October for fall colors",
    avgTemperature: { summer: "70-82°F (21-28°C)", winter: "10-28°F (-12--2°C)" },
    costOfLiving: "moderate",
    safetyRating: "high",
    funFact: "Wisconsin produces more cheese than any other state — over 3 billion pounds annually.",
    lastUpdated: new Date().toISOString(),
  },
  {
    name: "Louisiana",
    slug: "louisiana",
    abbreviation: "LA",
    capital: "Baton Rouge",
    population: 4657757,
    area: 52378,
    region: "South",
    nickname: "The Pelican State",
    motto: "Union, Justice, Confidence",
    bird: "Brown Pelican",
    flower: "Magnolia",
    tree: "Bald Cypress",
    statehood: "April 30, 1812 (18th state)",
    image: "https://images.unsplash.com/photo-1568967729548-e3be70f85720?w=800&q=80",
    flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Flag_of_Louisiana.svg/640px-Flag_of_Louisiana.svg.png",
    timezone: "Central (UTC-6)",
    majorCities: ["New Orleans", "Baton Rouge", "Shreveport", "Lafayette", "Lake Charles"],
    topAttractions: ["French Quarter", "Bourbon Street", "Swamp Tours", "Plantation Country", "Mardi Gras"],
    climate: "Humid subtropical with hot, humid summers and mild winters",
    bestTimeToVisit: "February-May for Mardi Gras and spring festivals; October-November for cooler weather",
    avgTemperature: { summer: "82-93°F (28-34°C)", winter: "42-60°F (6-16°C)" },
    costOfLiving: "low",
    safetyRating: "moderate",
    funFact: "Louisiana is the only state in the US that uses parishes instead of counties.",
    lastUpdated: new Date().toISOString(),
  },
  {
    name: "South Carolina",
    slug: "south-carolina",
    abbreviation: "SC",
    capital: "Columbia",
    population: 5118425,
    area: 32020,
    region: "South",
    nickname: "The Palmetto State",
    motto: "While I Breathe, I Hope",
    bird: "Carolina Wren",
    flower: "Yellow Jessamine",
    tree: "Sabal Palmetto",
    statehood: "May 23, 1788 (8th state)",
    image: "https://images.unsplash.com/photo-1590523741831-ab7e8b8f9c7f?w=800&q=80",
    flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Flag_of_South_Carolina.svg/640px-Flag_of_South_Carolina.svg.png",
    timezone: "Eastern (UTC-5)",
    majorCities: ["Charleston", "Columbia", "Myrtle Beach", "Greenville", "Hilton Head"],
    topAttractions: ["Charleston Historic District", "Myrtle Beach", "Hilton Head Island", "Fort Sumter", "Congaree National Park"],
    climate: "Humid subtropical with hot summers and mild winters",
    bestTimeToVisit: "March-May and September-November for comfortable temperatures",
    avgTemperature: { summer: "80-92°F (27-33°C)", winter: "35-56°F (2-13°C)" },
    costOfLiving: "low",
    safetyRating: "high",
    funFact: "Charleston was named the best city in the US by Travel + Leisure multiple years running.",
    lastUpdated: new Date().toISOString(),
  },
  {
    name: "Utah",
    slug: "utah",
    abbreviation: "UT",
    capital: "Salt Lake City",
    population: 3271616,
    area: 84899,
    region: "West",
    nickname: "The Beehive State",
    motto: "Industry",
    bird: "California Gull",
    flower: "Sego Lily",
    tree: "Quaking Aspen",
    statehood: "January 4, 1896 (45th state)",
    image: "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=800&q=80",
    flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Flag_of_Utah.svg/640px-Flag_of_Utah.svg.png",
    timezone: "Mountain (UTC-7)",
    majorCities: ["Salt Lake City", "Provo", "West Valley City", "St. George", "Park City"],
    topAttractions: ["Zion National Park", "Bryce Canyon", "Arches National Park", "Park City Ski Resort", "Monument Valley"],
    climate: "Arid to semi-arid; cold winters in mountains, hot summers in south",
    bestTimeToVisit: "March-May and September-November for national parks; December-March for skiing",
    avgTemperature: { summer: "80-100°F (27-38°C)", winter: "25-40°F (-4-4°C)" },
    costOfLiving: "moderate",
    safetyRating: "very-high",
    funFact: "Utah has the 'Mighty Five' — five stunning national parks all in one state.",
    lastUpdated: new Date().toISOString(),
  },
  {
    name: "Maine",
    slug: "maine",
    abbreviation: "ME",
    capital: "Augusta",
    population: 1362359,
    area: 35380,
    region: "Northeast",
    nickname: "The Pine Tree State",
    motto: "Dirigo (I Lead)",
    bird: "Black-capped Chickadee",
    flower: "White Pine Cone and Tassel",
    tree: "Eastern White Pine",
    statehood: "March 15, 1820 (23rd state)",
    image: "https://images.unsplash.com/photo-1501439088641-25d5aa3b40f0?w=800&q=80",
    flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Flag_of_Maine.svg/640px-Flag_of_Maine.svg.png",
    timezone: "Eastern (UTC-5)",
    majorCities: ["Portland", "Lewiston", "Bangor", "Augusta", "Bar Harbor"],
    topAttractions: ["Acadia National Park", "Portland Head Light", "Bar Harbor", "Camden", "Kennebunkport"],
    climate: "Humid continental with warm summers and cold, snowy winters",
    bestTimeToVisit: "June-October for warm weather and fall foliage",
    avgTemperature: { summer: "65-80°F (18-27°C)", winter: "15-32°F (-9-0°C)" },
    costOfLiving: "moderate",
    safetyRating: "very-high",
    funFact: "Maine produces 90% of the nation's lobster supply.",
    lastUpdated: new Date().toISOString(),
  },
  {
    name: "New Jersey",
    slug: "new-jersey",
    abbreviation: "NJ",
    capital: "Trenton",
    population: 9288994,
    area: 8723,
    region: "Northeast",
    nickname: "The Garden State",
    motto: "Liberty and Prosperity",
    bird: "Eastern Goldfinch",
    flower: "Common Blue Violet",
    tree: "Northern Red Oak",
    statehood: "December 18, 1787 (3rd state)",
    image: "https://images.unsplash.com/photo-1567359781514-3b964e2b04d6?w=800&q=80",
    flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Flag_of_New_Jersey.svg/640px-Flag_of_New_Jersey.svg.png",
    timezone: "Eastern (UTC-5)",
    majorCities: ["Newark", "Jersey City", "Trenton", "Atlantic City", "Princeton"],
    topAttractions: ["Atlantic City Boardwalk", "Liberty State Park", "Cape May", "Princeton University", "Jersey Shore"],
    climate: "Humid subtropical in south; humid continental in north",
    bestTimeToVisit: "May-June and September-October for pleasant weather",
    avgTemperature: { summer: "75-87°F (24-31°C)", winter: "25-40°F (-4-4°C)" },
    costOfLiving: "very-high",
    safetyRating: "high",
    funFact: "New Jersey has the most diners in the world and is often called the 'Diner Capital of the World.'",
    lastUpdated: new Date().toISOString(),
  },
  {
    name: "Iowa",
    slug: "iowa",
    abbreviation: "IA",
    capital: "Des Moines",
    population: 3190369,
    area: 56273,
    region: "Midwest",
    nickname: "The Hawkeye State",
    motto: "Our Liberties We Prize and Our Rights We Will Maintain",
    bird: "Eastern Goldfinch",
    flower: "Wild Prairie Rose",
    tree: "Bur Oak",
    statehood: "December 28, 1846 (29th state)",
    image: "https://images.unsplash.com/photo-1625244724120-1fd1d34d00f6?w=800&q=80",
    flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Flag_of_Iowa.svg/640px-Flag_of_Iowa.svg.png",
    timezone: "Central (UTC-6)",
    majorCities: ["Des Moines", "Cedar Rapids", "Davenport", "Iowa City", "Sioux City"],
    topAttractions: ["Maquoketa Caves", "Field of Dreams", "Effigy Mounds", "Iowa State Fair", "Amana Colonies"],
    climate: "Humid continental with hot summers and cold winters",
    bestTimeToVisit: "May-September for warm weather; August for the Iowa State Fair",
    avgTemperature: { summer: "72-86°F (22-30°C)", winter: "12-30°F (-11--1°C)" },
    costOfLiving: "low",
    safetyRating: "very-high",
    funFact: "Iowa produces more corn and pork than any other state in the nation.",
    lastUpdated: new Date().toISOString(),
  },
  {
    name: "New Mexico",
    slug: "new-mexico",
    abbreviation: "NM",
    capital: "Santa Fe",
    population: 2117522,
    area: 121590,
    region: "West",
    nickname: "Land of Enchantment",
    motto: "Crescit Eundo (It Grows as It Goes)",
    bird: "Greater Roadrunner",
    flower: "Yucca",
    tree: "Pinon Pine",
    statehood: "January 6, 1912 (47th state)",
    image: "https://images.unsplash.com/photo-1518098268026-4e89f1a2cd8e?w=800&q=80",
    flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Flag_of_New_Mexico.svg/640px-Flag_of_New_Mexico.svg.png",
    timezone: "Mountain (UTC-7)",
    majorCities: ["Albuquerque", "Santa Fe", "Las Cruces", "Rio Rancho", "Roswell"],
    topAttractions: ["Carlsbad Caverns", "White Sands", "Santa Fe Plaza", "Bandelier", "Taos Pueblo"],
    climate: "Arid to semi-arid with hot summers and mild winters; cooler at higher elevations",
    bestTimeToVisit: "September-November for pleasant weather and balloon festivals",
    avgTemperature: { summer: "80-95°F (27-35°C)", winter: "30-50°F (-1-10°C)" },
    costOfLiving: "low",
    safetyRating: "moderate",
    funFact: "Santa Fe is the oldest capital city in the United States, founded in 1610.",
    lastUpdated: new Date().toISOString(),
  },
  {
    name: "Kentucky",
    slug: "kentucky",
    abbreviation: "KY",
    capital: "Frankfort",
    population: 4505836,
    area: 40408,
    region: "South",
    nickname: "The Bluegrass State",
    motto: "United We Stand, Divided We Fall",
    bird: "Northern Cardinal",
    flower: "Goldenrod",
    tree: "Tulip Poplar",
    statehood: "June 1, 1792 (15th state)",
    image: "https://images.unsplash.com/photo-1548786811-dd6e453ccca7?w=800&q=80",
    flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Flag_of_Kentucky.svg/640px-Flag_of_Kentucky.svg.png",
    timezone: "Eastern/Central (UTC-5/UTC-6)",
    majorCities: ["Louisville", "Lexington", "Bowling Green", "Frankfort", "Covington"],
    topAttractions: ["Mammoth Cave National Park", "Kentucky Derby", "Bourbon Trail", "Red River Gorge", "Cumberland Falls"],
    climate: "Humid subtropical with hot summers and moderately cold winters",
    bestTimeToVisit: "April-May for Derby season and spring; September-October for fall colors",
    avgTemperature: { summer: "78-90°F (26-32°C)", winter: "28-42°F (-2-6°C)" },
    costOfLiving: "low",
    safetyRating: "high",
    funFact: "95% of the world's bourbon is produced in Kentucky.",
    lastUpdated: new Date().toISOString(),
  },
  {
    name: "Connecticut",
    slug: "connecticut",
    abbreviation: "CT",
    capital: "Hartford",
    population: 3605944,
    area: 5543,
    region: "Northeast",
    nickname: "The Constitution State",
    motto: "Qui Transtulit Sustinet (He Who Transplanted Still Sustains)",
    bird: "American Robin",
    flower: "Mountain Laurel",
    tree: "White Oak",
    statehood: "January 9, 1788 (5th state)",
    image: "https://images.unsplash.com/photo-1572120360610-d971b9d7767c?w=800&q=80",
    flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Flag_of_Connecticut.svg/640px-Flag_of_Connecticut.svg.png",
    timezone: "Eastern (UTC-5)",
    majorCities: ["Bridgeport", "New Haven", "Hartford", "Stamford", "Waterbury"],
    topAttractions: ["Yale University", "Mystic Seaport", "Mark Twain House", "Gillette Castle", "Essex Steam Train"],
    climate: "Humid continental with warm summers and cold winters",
    bestTimeToVisit: "September-October for spectacular fall foliage; June-August for coast",
    avgTemperature: { summer: "72-84°F (22-29°C)", winter: "22-36°F (-6-2°C)" },
    costOfLiving: "very-high",
    safetyRating: "high",
    funFact: "Connecticut is home to the first hamburger (1900), Frisbee (1957), and lollipop (1908).",
    lastUpdated: new Date().toISOString(),
  },
  {
    name: "Maryland",
    slug: "maryland",
    abbreviation: "MD",
    capital: "Annapolis",
    population: 6177224,
    area: 12406,
    region: "South",
    nickname: "The Old Line State",
    motto: "Fatti Maschii, Parole Femine (Strong Deeds, Gentle Words)",
    bird: "Baltimore Oriole",
    flower: "Black-Eyed Susan",
    tree: "White Oak",
    statehood: "April 28, 1788 (7th state)",
    image: "https://images.unsplash.com/photo-1575505586569-646b2ca898fc?w=800&q=80",
    flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Flag_of_Maryland.svg/640px-Flag_of_Maryland.svg.png",
    timezone: "Eastern (UTC-5)",
    majorCities: ["Baltimore", "Annapolis", "Frederick", "Rockville", "Ocean City"],
    topAttractions: ["Inner Harbor", "Assateague Island", "Chesapeake Bay", "Antietam Battlefield", "Ocean City"],
    climate: "Humid subtropical with hot summers and cool winters",
    bestTimeToVisit: "April-June and September-November for pleasant weather",
    avgTemperature: { summer: "76-88°F (24-31°C)", winter: "28-42°F (-2-6°C)" },
    costOfLiving: "high",
    safetyRating: "high",
    funFact: "Maryland is known as 'America's Sailing Capital' with Annapolis at its heart.",
    lastUpdated: new Date().toISOString(),
  },
  {
    name: "Indiana",
    slug: "indiana",
    abbreviation: "IN",
    capital: "Indianapolis",
    population: 6833037,
    area: 36420,
    region: "Midwest",
    nickname: "The Hoosier State",
    motto: "The Crossroads of America",
    bird: "Northern Cardinal",
    flower: "Peony",
    tree: "Tulip Tree",
    statehood: "December 11, 1816 (19th state)",
    image: "https://images.unsplash.com/photo-1588693635785-992a0bf3dc27?w=800&q=80",
    flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/Flag_of_Indiana.svg/640px-Flag_of_Indiana.svg.png",
    timezone: "Eastern (UTC-5)",
    majorCities: ["Indianapolis", "Fort Wayne", "Evansville", "South Bend", "Bloomington"],
    topAttractions: ["Indianapolis Motor Speedway", "Indiana Dunes", "Children's Museum of Indianapolis", "Brown County State Park", "French Lick"],
    climate: "Humid continental with hot summers and cold winters",
    bestTimeToVisit: "May for the Indy 500; September-October for fall foliage",
    avgTemperature: { summer: "74-86°F (23-30°C)", winter: "22-36°F (-6-2°C)" },
    costOfLiving: "low",
    safetyRating: "high",
    funFact: "The Indianapolis 500, held annually since 1911, is the largest single-day sporting event in the world.",
    lastUpdated: new Date().toISOString(),
  },
  {
    name: "Missouri",
    slug: "missouri",
    abbreviation: "MO",
    capital: "Jefferson City",
    population: 6154913,
    area: 69707,
    region: "Midwest",
    nickname: "The Show-Me State",
    motto: "Salus Populi Suprema Lex Esto (The Welfare of the People Shall Be the Supreme Law)",
    bird: "Eastern Bluebird",
    flower: "White Hawthorn Blossom",
    tree: "Flowering Dogwood",
    statehood: "August 10, 1821 (24th state)",
    image: "https://images.unsplash.com/photo-1603118281919-49c69f685a2e?w=800&q=80",
    flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Flag_of_Missouri.svg/640px-Flag_of_Missouri.svg.png",
    timezone: "Central (UTC-6)",
    majorCities: ["Kansas City", "St. Louis", "Springfield", "Columbia", "Jefferson City"],
    topAttractions: ["Gateway Arch", "Branson", "Lake of the Ozarks", "Kansas City BBQ Trail", "Mark Twain Boyhood Home"],
    climate: "Humid continental/subtropical with hot summers and cold winters",
    bestTimeToVisit: "April-May and September-October for comfortable weather",
    avgTemperature: { summer: "78-90°F (26-32°C)", winter: "24-40°F (-4-4°C)" },
    costOfLiving: "low",
    safetyRating: "high",
    funFact: "The Gateway Arch in St. Louis is the tallest man-made monument in the United States at 630 feet.",
    lastUpdated: new Date().toISOString(),
  },
  {
    name: "Oklahoma",
    slug: "oklahoma",
    abbreviation: "OK",
    capital: "Oklahoma City",
    population: 3959353,
    area: 69899,
    region: "South",
    nickname: "The Sooner State",
    motto: "Labor Omnia Vincit (Labor Conquers All Things)",
    bird: "Scissor-tailed Flycatcher",
    flower: "Oklahoma Rose",
    tree: "Eastern Redbud",
    statehood: "November 16, 1907 (46th state)",
    image: "https://images.unsplash.com/photo-1568992687947-868a62a9f521?w=800&q=80",
    flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Flag_of_Oklahoma.svg/640px-Flag_of_Oklahoma.svg.png",
    timezone: "Central (UTC-6)",
    majorCities: ["Oklahoma City", "Tulsa", "Norman", "Broken Arrow", "Edmond"],
    topAttractions: ["Oklahoma City National Memorial", "Philbrook Museum", "Turner Falls", "Route 66 Museum", "Wichita Mountains"],
    climate: "Humid subtropical with hot summers, mild winters, and frequent severe weather",
    bestTimeToVisit: "March-May and October-November; avoid tornado season (April-June)",
    avgTemperature: { summer: "80-95°F (27-35°C)", winter: "30-50°F (-1-10°C)" },
    costOfLiving: "low",
    safetyRating: "high",
    funFact: "Oklahoma has more man-made lakes than any other state, with over 200.",
    lastUpdated: new Date().toISOString(),
  },
  {
    name: "Arkansas",
    slug: "arkansas",
    abbreviation: "AR",
    capital: "Little Rock",
    population: 3011524,
    area: 53179,
    region: "South",
    nickname: "The Natural State",
    motto: "Regnat Populus (The People Rule)",
    bird: "Northern Mockingbird",
    flower: "Apple Blossom",
    tree: "Loblolly Pine",
    statehood: "June 15, 1836 (25th state)",
    image: "https://images.unsplash.com/photo-1584483766114-2cea6facdf57?w=800&q=80",
    flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Flag_of_Arkansas.svg/640px-Flag_of_Arkansas.svg.png",
    timezone: "Central (UTC-6)",
    majorCities: ["Little Rock", "Fort Smith", "Fayetteville", "Springdale", "Hot Springs"],
    topAttractions: ["Hot Springs National Park", "Crater of Diamonds State Park", "Buffalo National River", "Crystal Bridges Museum", "Blanchard Springs Caverns"],
    climate: "Humid subtropical with hot summers and mild winters",
    bestTimeToVisit: "March-May and September-November for mild weather",
    avgTemperature: { summer: "80-93°F (27-34°C)", winter: "32-50°F (0-10°C)" },
    costOfLiving: "low",
    safetyRating: "high",
    funFact: "Crater of Diamonds State Park is the only place in the world where the public can search for real diamonds.",
    lastUpdated: new Date().toISOString(),
  },
  {
    name: "Mississippi",
    slug: "mississippi",
    abbreviation: "MS",
    capital: "Jackson",
    population: 2961279,
    area: 48432,
    region: "South",
    nickname: "The Magnolia State",
    motto: "Virtute et Armis (By Valor and Arms)",
    bird: "Northern Mockingbird",
    flower: "Magnolia",
    tree: "Magnolia",
    statehood: "December 10, 1817 (20th state)",
    image: "https://images.unsplash.com/photo-1565043666747-69f6646db940?w=800&q=80",
    flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/Flag_of_Mississippi.svg/640px-Flag_of_Mississippi.svg.png",
    timezone: "Central (UTC-6)",
    majorCities: ["Jackson", "Gulfport", "Biloxi", "Hattiesburg", "Oxford"],
    topAttractions: ["Natchez Trace Parkway", "Vicksburg National Military Park", "Gulf Islands National Seashore", "Mississippi Blues Trail", "Oxford Square"],
    climate: "Humid subtropical with hot, humid summers and mild winters",
    bestTimeToVisit: "March-May and October-November for comfortable weather",
    avgTemperature: { summer: "80-93°F (27-34°C)", winter: "38-55°F (3-13°C)" },
    costOfLiving: "low",
    safetyRating: "moderate",
    funFact: "Mississippi is the birthplace of the blues, with the Mississippi Delta being its spiritual home.",
    lastUpdated: new Date().toISOString(),
  },
  {
    name: "Alabama",
    slug: "alabama",
    abbreviation: "AL",
    capital: "Montgomery",
    population: 5024279,
    area: 52420,
    region: "South",
    nickname: "The Yellowhammer State",
    motto: "Audemus Jura Nostra Defendere (We Dare Defend Our Rights)",
    bird: "Yellowhammer (Northern Flicker)",
    flower: "Camellia",
    tree: "Longleaf Pine",
    statehood: "December 14, 1819 (22nd state)",
    image: "https://images.unsplash.com/photo-1581369692682-e05c3e40bea3?w=800&q=80",
    flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_Alabama.svg/640px-Flag_of_Alabama.svg.png",
    timezone: "Central (UTC-6)",
    majorCities: ["Birmingham", "Montgomery", "Huntsville", "Mobile", "Tuscaloosa"],
    topAttractions: ["US Space & Rocket Center", "Gulf Shores", "Civil Rights Trail", "Cheaha Mountain", "USS Alabama Battleship"],
    climate: "Humid subtropical with hot summers and mild winters",
    bestTimeToVisit: "March-May and September-November for pleasant weather",
    avgTemperature: { summer: "80-93°F (27-34°C)", winter: "35-55°F (2-13°C)" },
    costOfLiving: "low",
    safetyRating: "high",
    funFact: "Huntsville, Alabama built the rocket that carried the first humans to the Moon.",
    lastUpdated: new Date().toISOString(),
  },
  {
    name: "Nebraska",
    slug: "nebraska",
    abbreviation: "NE",
    capital: "Lincoln",
    population: 1961504,
    area: 77348,
    region: "Midwest",
    nickname: "The Cornhusker State",
    motto: "Equality Before the Law",
    bird: "Western Meadowlark",
    flower: "Goldenrod",
    tree: "Eastern Cottonwood",
    statehood: "March 1, 1867 (37th state)",
    image: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&q=80",
    flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Flag_of_Nebraska.svg/640px-Flag_of_Nebraska.svg.png",
    timezone: "Central/Mountain (UTC-6/UTC-7)",
    majorCities: ["Omaha", "Lincoln", "Bellevue", "Grand Island", "Kearney"],
    topAttractions: ["Chimney Rock", "Henry Doorly Zoo", "Carhenge", "Scotts Bluff", "Sandhills"],
    climate: "Continental with hot summers and cold winters; severe weather common",
    bestTimeToVisit: "May-June and September-October for mild weather",
    avgTemperature: { summer: "75-90°F (24-32°C)", winter: "15-35°F (-9-2°C)" },
    costOfLiving: "low",
    safetyRating: "high",
    funFact: "Nebraska's unicameral legislature is the only one-house state legislature in the United States.",
    lastUpdated: new Date().toISOString(),
  },
  {
    name: "Kansas",
    slug: "kansas",
    abbreviation: "KS",
    capital: "Topeka",
    population: 2937880,
    area: 82278,
    region: "Midwest",
    nickname: "The Sunflower State",
    motto: "Ad Astra per Aspera (To the Stars Through Difficulties)",
    bird: "Western Meadowlark",
    flower: "Sunflower",
    tree: "Eastern Cottonwood",
    statehood: "January 29, 1861 (34th state)",
    image: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&q=80",
    flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Flag_of_Kansas.svg/640px-Flag_of_Kansas.svg.png",
    timezone: "Central/Mountain (UTC-6/UTC-7)",
    majorCities: ["Wichita", "Overland Park", "Kansas City", "Topeka", "Lawrence"],
    topAttractions: ["Flint Hills", "Cosmosphere", "Boot Hill Museum", "Tallgrass Prairie", "Monument Rocks"],
    climate: "Continental with hot summers, cold winters, and frequent severe weather",
    bestTimeToVisit: "April-May and September-October for mild weather; avoid tornado season",
    avgTemperature: { summer: "78-93°F (26-34°C)", winter: "20-40°F (-7-4°C)" },
    costOfLiving: "low",
    safetyRating: "high",
    funFact: "Kansas really is flatter than a pancake — a 2003 study by geography professors actually confirmed this.",
    lastUpdated: new Date().toISOString(),
  },
  {
    name: "West Virginia",
    slug: "west-virginia",
    abbreviation: "WV",
    capital: "Charleston",
    population: 1793716,
    area: 24230,
    region: "South",
    nickname: "The Mountain State",
    motto: "Montani Semper Liberi (Mountaineers Are Always Free)",
    bird: "Northern Cardinal",
    flower: "Rhododendron",
    tree: "Sugar Maple",
    statehood: "June 20, 1863 (35th state)",
    image: "https://images.unsplash.com/photo-1563299796-17596ed6b017?w=800&q=80",
    flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Flag_of_West_Virginia.svg/640px-Flag_of_West_Virginia.svg.png",
    timezone: "Eastern (UTC-5)",
    majorCities: ["Charleston", "Huntington", "Morgantown", "Parkersburg", "Wheeling"],
    topAttractions: ["New River Gorge", "Seneca Rocks", "Blackwater Falls", "Greenbrier Resort", "Cass Scenic Railroad"],
    climate: "Humid continental/subtropical with warm summers and cold, snowy winters in mountains",
    bestTimeToVisit: "June-August for rafting; October for stunning fall foliage",
    avgTemperature: { summer: "72-86°F (22-30°C)", winter: "24-40°F (-4-4°C)" },
    costOfLiving: "low",
    safetyRating: "high",
    funFact: "The New River in West Virginia is actually one of the oldest rivers in the world, estimated at 360 million years old.",
    lastUpdated: new Date().toISOString(),
  },
  {
    name: "Idaho",
    slug: "idaho",
    abbreviation: "ID",
    capital: "Boise",
    population: 1900923,
    area: 83569,
    region: "West",
    nickname: "The Gem State",
    motto: "Esto Perpetua (Let It Be Perpetual)",
    bird: "Mountain Bluebird",
    flower: "Syringa",
    tree: "Western White Pine",
    statehood: "July 3, 1890 (43rd state)",
    image: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=800&q=80",
    flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Flag_of_Idaho.svg/640px-Flag_of_Idaho.svg.png",
    timezone: "Mountain (UTC-7)",
    majorCities: ["Boise", "Meridian", "Nampa", "Idaho Falls", "Coeur d'Alene"],
    topAttractions: ["Craters of the Moon", "Sun Valley", "Shoshone Falls", "Sawtooth Mountains", "Coeur d'Alene Lake"],
    climate: "Semi-arid continental; cold winters and warm, dry summers",
    bestTimeToVisit: "June-September for outdoor activities; December-March for skiing",
    avgTemperature: { summer: "70-90°F (21-32°C)", winter: "20-36°F (-7-2°C)" },
    costOfLiving: "moderate",
    safetyRating: "very-high",
    funFact: "Idaho produces about one-third of all potatoes grown in the United States.",
    lastUpdated: new Date().toISOString(),
  },
  {
    name: "Wyoming",
    slug: "wyoming",
    abbreviation: "WY",
    capital: "Cheyenne",
    population: 576851,
    area: 97813,
    region: "West",
    nickname: "The Equality State",
    motto: "Equal Rights",
    bird: "Western Meadowlark",
    flower: "Indian Paintbrush",
    tree: "Plains Cottonwood",
    statehood: "July 10, 1890 (44th state)",
    image: "https://images.unsplash.com/photo-1504870712516-3f8a0c7adfe8?w=800&q=80",
    flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Flag_of_Wyoming.svg/640px-Flag_of_Wyoming.svg.png",
    timezone: "Mountain (UTC-7)",
    majorCities: ["Cheyenne", "Casper", "Laramie", "Gillette", "Jackson"],
    topAttractions: ["Yellowstone National Park", "Grand Teton National Park", "Devils Tower", "Jackson Hole", "Wind River Range"],
    climate: "Semi-arid continental with cold winters and warm, short summers",
    bestTimeToVisit: "June-September for national parks and warm weather",
    avgTemperature: { summer: "65-85°F (18-29°C)", winter: "10-30°F (-12--1°C)" },
    costOfLiving: "moderate",
    safetyRating: "very-high",
    funFact: "Wyoming was the first state to grant women the right to vote in 1869, earning its nickname 'The Equality State.'",
    lastUpdated: new Date().toISOString(),
  },
  {
    name: "New Hampshire",
    slug: "new-hampshire",
    abbreviation: "NH",
    capital: "Concord",
    population: 1377529,
    area: 9349,
    region: "Northeast",
    nickname: "The Granite State",
    motto: "Live Free or Die",
    bird: "Purple Finch",
    flower: "Purple Lilac",
    tree: "White Birch",
    statehood: "June 21, 1788 (9th state)",
    image: "https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=800&q=80",
    flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/Flag_of_New_Hampshire.svg/640px-Flag_of_New_Hampshire.svg.png",
    timezone: "Eastern (UTC-5)",
    majorCities: ["Manchester", "Nashua", "Concord", "Portsmouth", "Hanover"],
    topAttractions: ["White Mountains", "Mount Washington", "Franconia Notch", "Lake Winnipesaukee", "Portsmouth Historic District"],
    climate: "Humid continental with warm summers and cold, snowy winters",
    bestTimeToVisit: "September-October for peak fall foliage; June-August for lakes and hiking",
    avgTemperature: { summer: "68-82°F (20-28°C)", winter: "12-30°F (-11--1°C)" },
    costOfLiving: "high",
    safetyRating: "very-high",
    funFact: "New Hampshire has no state income tax and no state sales tax, making it popular for tax-free shopping.",
    lastUpdated: new Date().toISOString(),
  },
  {
    name: "Vermont",
    slug: "vermont",
    abbreviation: "VT",
    capital: "Montpelier",
    population: 643077,
    area: 9616,
    region: "Northeast",
    nickname: "The Green Mountain State",
    motto: "Freedom and Unity",
    bird: "Hermit Thrush",
    flower: "Red Clover",
    tree: "Sugar Maple",
    statehood: "March 4, 1791 (14th state)",
    image: "https://images.unsplash.com/photo-1569982175971-d92b01cf8694?w=800&q=80",
    flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Flag_of_Vermont.svg/640px-Flag_of_Vermont.svg.png",
    timezone: "Eastern (UTC-5)",
    majorCities: ["Burlington", "South Burlington", "Rutland", "Montpelier", "Stowe"],
    topAttractions: ["Stowe", "Green Mountains", "Ben & Jerry's Factory", "Shelburne Farms", "Church Street Marketplace"],
    climate: "Humid continental with warm summers and cold, snowy winters",
    bestTimeToVisit: "September-October for spectacular fall foliage; January-March for skiing",
    avgTemperature: { summer: "66-80°F (19-27°C)", winter: "10-28°F (-12--2°C)" },
    costOfLiving: "high",
    safetyRating: "very-high",
    funFact: "Vermont produces more maple syrup than any other state — about 50% of the US supply.",
    lastUpdated: new Date().toISOString(),
  },
  {
    name: "Delaware",
    slug: "delaware",
    abbreviation: "DE",
    capital: "Dover",
    population: 989948,
    area: 2489,
    region: "South",
    nickname: "The First State",
    motto: "Liberty and Independence",
    bird: "Blue Hen Chicken",
    flower: "Peach Blossom",
    tree: "American Holly",
    statehood: "December 7, 1787 (1st state)",
    image: "https://images.unsplash.com/photo-1499092346589-b9b6be3e94b2?w=800&q=80",
    flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/Flag_of_Delaware.svg/640px-Flag_of_Delaware.svg.png",
    timezone: "Eastern (UTC-5)",
    majorCities: ["Wilmington", "Dover", "Newark", "Rehoboth Beach", "Lewes"],
    topAttractions: ["Rehoboth Beach", "Winterthur Museum", "Hagley Museum", "Cape Henlopen", "Brandywine Valley"],
    climate: "Humid subtropical with hot summers and cool winters",
    bestTimeToVisit: "May-September for beaches; October for fall festivals",
    avgTemperature: { summer: "74-87°F (23-31°C)", winter: "28-42°F (-2-6°C)" },
    costOfLiving: "moderate",
    safetyRating: "high",
    funFact: "Delaware was the first state to ratify the US Constitution on December 7, 1787.",
    lastUpdated: new Date().toISOString(),
  },
  {
    name: "Rhode Island",
    slug: "rhode-island",
    abbreviation: "RI",
    capital: "Providence",
    population: 1097379,
    area: 1545,
    region: "Northeast",
    nickname: "The Ocean State",
    motto: "Hope",
    bird: "Rhode Island Red",
    flower: "Violet",
    tree: "Red Maple",
    statehood: "May 29, 1790 (13th state)",
    image: "https://images.unsplash.com/photo-1545579133-99bb5ab189bd?w=800&q=80",
    flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Flag_of_Rhode_Island.svg/640px-Flag_of_Rhode_Island.svg.png",
    timezone: "Eastern (UTC-5)",
    majorCities: ["Providence", "Warwick", "Cranston", "Newport", "Pawtucket"],
    topAttractions: ["Newport Mansions", "WaterFire Providence", "Block Island", "Cliff Walk", "Roger Williams Park"],
    climate: "Humid continental with warm summers and cold winters; ocean moderated",
    bestTimeToVisit: "June-September for beaches; October for fall foliage",
    avgTemperature: { summer: "70-82°F (21-28°C)", winter: "24-38°F (-4-3°C)" },
    costOfLiving: "high",
    safetyRating: "high",
    funFact: "Rhode Island is the smallest US state but has the longest official name: State of Rhode Island and Providence Plantations.",
    lastUpdated: new Date().toISOString(),
  },
  {
    name: "South Dakota",
    slug: "south-dakota",
    abbreviation: "SD",
    capital: "Pierre",
    population: 886667,
    area: 77116,
    region: "Midwest",
    nickname: "The Mount Rushmore State",
    motto: "Under God the People Rule",
    bird: "Ring-necked Pheasant",
    flower: "Pasque Flower",
    tree: "Black Hills Spruce",
    statehood: "November 2, 1889 (40th state)",
    image: "https://images.unsplash.com/photo-1558882224-dda166ffe592?w=800&q=80",
    flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Flag_of_South_Dakota.svg/640px-Flag_of_South_Dakota.svg.png",
    timezone: "Central/Mountain (UTC-6/UTC-7)",
    majorCities: ["Sioux Falls", "Rapid City", "Pierre", "Deadwood", "Brookings"],
    topAttractions: ["Mount Rushmore", "Badlands National Park", "Crazy Horse Memorial", "Custer State Park", "Deadwood"],
    climate: "Continental with extreme temperature variations; cold winters and warm summers",
    bestTimeToVisit: "June-August for warm weather and national parks",
    avgTemperature: { summer: "70-88°F (21-31°C)", winter: "10-30°F (-12--1°C)" },
    costOfLiving: "low",
    safetyRating: "very-high",
    funFact: "Mount Rushmore took 14 years to carve and features the 60-foot faces of four US Presidents.",
    lastUpdated: new Date().toISOString(),
  },
  {
    name: "North Dakota",
    slug: "north-dakota",
    abbreviation: "ND",
    capital: "Bismarck",
    population: 779094,
    area: 70698,
    region: "Midwest",
    nickname: "The Peace Garden State",
    motto: "Liberty and Union, Now and Forever, One and Inseparable",
    bird: "Western Meadowlark",
    flower: "Wild Prairie Rose",
    tree: "American Elm",
    statehood: "November 2, 1889 (39th state)",
    image: "https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?w=800&q=80",
    flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/Flag_of_North_Dakota.svg/640px-Flag_of_North_Dakota.svg.png",
    timezone: "Central/Mountain (UTC-6/UTC-7)",
    majorCities: ["Fargo", "Bismarck", "Grand Forks", "Minot", "Williston"],
    topAttractions: ["Theodore Roosevelt National Park", "International Peace Garden", "Medora Musical", "Enchanted Highway", "Fargo-Moorhead"],
    climate: "Continental with very cold winters and warm, short summers",
    bestTimeToVisit: "June-August for pleasant weather; avoid harsh winters",
    avgTemperature: { summer: "65-84°F (18-29°C)", winter: "0-22°F (-18--6°C)" },
    costOfLiving: "low",
    safetyRating: "very-high",
    funFact: "North Dakota produces more sunflowers than any other state and is one of the top honey producers.",
    lastUpdated: new Date().toISOString(),
  },
];

export function getStateBySlug(slug: string): USState | undefined {
  return statesData.find((s) => s.slug === slug);
}

export function getStatesByRegion(region: string): USState[] {
  return statesData.filter((s) => s.region === region);
}

export function searchStates(query: string): USState[] {
  const q = query.toLowerCase();
  return statesData.filter(
    (s) =>
      s.name.toLowerCase().includes(q) ||
      s.capital.toLowerCase().includes(q) ||
      s.nickname.toLowerCase().includes(q) ||
      s.region.toLowerCase().includes(q)
  );
}
