export const tipCategories = [
  {
    title: "Before You Go",
    icon: "FileText",
    color: "bg-blue-50 text-blue-600",
    tips: [
      { title: "Check passport expiration", detail: "Many countries require at least 6 months validity. Renew early — processing takes 6-8 weeks." },
      { title: "Research visa requirements", detail: "Visa rules vary by nationality. Check embassy websites or our country pages for up-to-date info." },
      { title: "Get travel insurance", detail: "Buy comprehensive coverage for medical emergencies, cancellation, and lost luggage." },
      { title: "Register with your embassy", detail: "Register your trip so they can reach you in emergencies (e.g., STEP for US citizens)." },
      { title: "Copy important documents", detail: "Make digital copies of passport, insurance, credit cards. Store in cloud and email to yourself." },
      { title: "Check health requirements", detail: "Visit a travel clinic 4-6 weeks before. Some destinations require specific vaccinations." },
    ],
  },
  {
    title: "Packing Smart",
    icon: "Luggage",
    color: "bg-purple-50 text-purple-600",
    tips: [
      { title: "Roll, don't fold", detail: "Rolling saves space and reduces wrinkles. Use packing cubes to organize." },
      { title: "Carry-on essentials kit", detail: "Medications, change of clothes, charger, toothbrush, documents — in case luggage is delayed." },
      { title: "Universal power adapter", detail: "Different countries use different plugs. A universal adapter with USB covers all bases." },
      { title: "Leave room for souvenirs", detail: "Pack light, leave 20% empty. Consider a foldable duffle bag." },
      { title: "Wear bulkiest items on plane", detail: "Heaviest shoes and jacket on the plane saves luggage space and weight." },
      { title: "Basic first aid kit", detail: "Band-aids, pain relievers, anti-diarrhea meds, antihistamines, prescriptions." },
    ],
  },
  {
    title: "Money & Budget",
    icon: "Wallet",
    color: "bg-green-50 text-green-600",
    tips: [
      { title: "Notify your bank", detail: "Tell bank and credit card companies your travel dates to avoid fraud blocks." },
      { title: "No-fee cards", detail: "Chase Sapphire, Capital One Venture charge no foreign transaction fees." },
      { title: "ATMs over exchange bureaus", detail: "Airport exchanges have worst rates. Use bank ATMs for better rates." },
      { title: "Book flights on Tuesdays", detail: "Tuesday afternoons often have lowest fares. Use Google Flights price tracking." },
      { title: "Eat where locals eat", detail: "Skip tourist restaurants. Ask hotel staff for popular local spots." },
      { title: "Use public transit", detail: "Buses, metros, trains are cheaper. Many cities offer tourist transit passes." },
    ],
  },
  {
    title: "Safety & Security",
    icon: "Shield",
    color: "bg-red-50 text-red-600",
    tips: [
      { title: "Guard valuables", detail: "Use front pockets, money belt, or crossbody bag in crowded tourist areas." },
      { title: "Share your itinerary", detail: "Give a trusted person your full itinerary, hotel addresses, and contacts." },
      { title: "Learn basic local phrases", detail: "'Hello,' 'thank you,' 'help,' 'how much?' shows respect and helps a lot." },
      { title: "Be cautious with public Wi-Fi", detail: "Avoid banking on public networks. Use a VPN for secure browsing." },
      { title: "Trust your instincts", detail: "If it feels wrong, leave. Watch for common scams like fake petitions." },
      { title: "Know emergency numbers", detail: "Save local numbers. 112 works in most of Europe. Check our country pages." },
    ],
  },
  {
    title: "Health & Wellness",
    icon: "Heart",
    color: "bg-pink-50 text-pink-600",
    tips: [
      { title: "Stay hydrated on flights", detail: "Cabin air is dry. Drink water, avoid alcohol, bring an empty bottle." },
      { title: "Beat jet lag", detail: "Shift sleep schedule before departure. Get sunlight on arrival." },
      { title: "Street food safety", detail: "Choose busy vendors. Ensure meat is cooked. Avoid raw veggies in developing countries." },
      { title: "Check tap water safety", detail: "Many countries have unsafe tap water. Use bottled for drinking and brushing teeth." },
      { title: "Sun and bug protection", detail: "SPF 30+ sunscreen and DEET repellent are essential in tropical areas." },
      { title: "Move on long flights", detail: "Walk every 1-2 hours. Do ankle circles to prevent DVT." },
    ],
  },
  {
    title: "Tech & Connectivity",
    icon: "Smartphone",
    color: "bg-amber-50 text-amber-600",
    tips: [
      { title: "Get an eSIM", detail: "International roaming is expensive. Try Airalo or Holafly for affordable data." },
      { title: "Download offline maps", detail: "Google Maps or Maps.me offline — essential when you lose signal." },
      { title: "Offline translator", detail: "Download Google Translate language packs. Camera translation is great for signs." },
      { title: "Portable battery pack", detail: "20,000mAh power bank charges your phone 4-5 times for long sightseeing days." },
      { title: "Back up photos daily", detail: "Upload to cloud each night. Don't risk losing memories to a lost phone." },
      { title: "Save info offline", detail: "Screenshot hotel addresses, confirmations, contacts for offline access." },
    ],
  },
];
